import tseslint from "typescript-eslint";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import { baseConfig } from "@hyperion/config/eslint";

export default tseslint.config(
  baseConfig,
  {
    // Generated by `msw init` - not our source.
    ignores: ["public/mockServiceWorker.js"],
  },
  {
    files: ["src/**/*.{ts,tsx}"],
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
    },
  },
  {
    // Config files run under Node outside the app's tsconfig project.
    files: ["*.config.{js,ts}"],
    ...tseslint.configs.disableTypeChecked,
  },
);
