import { z } from "zod";

/**
 * The 13 field types from docs/spec/Purchase-V2.md §4 ("client's own
 * definitions"). apps/web's schema-form field-type registry is keyed by
 * this enum — one component per value, never a switch outside the registry
 * (frontend rule 6).
 */
export const fieldTypeSchema = z.enum([
  "AutoGenerated",
  "Textbox",
  "TextArea",
  "Dropdown",
  "Lookup",
  "DatePicker",
  "Decimal",
  "Currency",
  "Percentage",
  "Toggle",
  "Calculated",
  "FileUpload",
  "MultiUpload",
]);
export type FieldType = z.infer<typeof fieldTypeSchema>;

/** CLAUDE.md's field model — Tier 3 (custom) is out of 16-week scope; the value exists so the contract doesn't have to change when it lands. */
export const fieldTierSchema = z.enum(["fixed", "configurable", "custom"]);
export type FieldTier = z.infer<typeof fieldTierSchema>;

/** The primitive the value is validated/stored as, independent of the widget (fieldType) that edits it. */
export const fieldDataTypeSchema = z.enum([
  "string",
  "number",
  "decimal",
  "boolean",
  "date",
  "enum",
  "uuid",
  "json",
]);
export type FieldDataType = z.infer<typeof fieldDataTypeSchema>;

/**
 * Where a Dropdown/Lookup's options come from. `dependsOn` is how cascading
 * dropdowns (Country -> City, per the spec) are expressed: the frontend
 * refetches this field's options whenever the named field's value changes.
 */
export const optionsSourceSchema = z.object({
  type: z.enum(["master", "enum", "static"]),
  master: z.string().optional(),
  dependsOn: z.string().optional(),
  staticOptions: z.array(z.object({ label: z.string(), value: z.string() })).optional(),
});
export type OptionsSource = z.infer<typeof optionsSourceSchema>;

/** Simple show/hide-on-another-field's-value condition, e.g. `{ field: "through", operator: "eq", value: "sea" }`. */
export const visibilityConditionSchema = z.object({
  field: z.string(),
  operator: z.enum(["eq", "neq", "in", "notIn"]),
  value: z.union([z.string(), z.number(), z.boolean(), z.array(z.string())]),
});
export type VisibilityCondition = z.infer<typeof visibilityConditionSchema>;

/**
 * One resolved field: code-declared defaults already merged with the
 * company's field_definitions override and the requesting user's field
 * permissions (core/field-engine's job, server-side only — frontend rule
 * 4). A field the user cannot view is simply absent from the response, not
 * present-but-hidden.
 */
export const fieldDefinitionSchema = z.object({
  fieldKey: z.string(),
  tier: fieldTierSchema,
  label: z.string(),
  fieldType: fieldTypeSchema,
  dataType: fieldDataTypeSchema,
  isMandatory: z.boolean(),
  isEditable: z.boolean(),
  isSystem: z.boolean(),
  sortOrder: z.number().int(),
  defaultValue: z.unknown().nullable().optional(),
  optionsSource: optionsSourceSchema.nullable().optional(),
  visibilityCondition: visibilityConditionSchema.nullable().optional(),
  validation: z.record(z.string(), z.unknown()).nullable().optional(),
});
export type FieldDefinition = z.infer<typeof fieldDefinitionSchema>;

/** A form section, e.g. "Purchase Header", "Shipment Details" — rendered as an AntD Card/Collapse per FE-3. */
export const fieldSectionSchema = z.object({
  key: z.string(),
  label: z.string(),
  sortOrder: z.number().int(),
  fields: z.array(fieldDefinitionSchema),
});
export type FieldSection = z.infer<typeof fieldSectionSchema>;

// --- GET /api/v1/field-definitions/:module/:entity -------------------------

/**
 * `version` is the field-engine's field_version — compile-validator.ts
 * memoizes the runtime-compiled Zod schema by (module, entity, version) so
 * a field_definition.changed event invalidation produces a fresh schema
 * instead of a stale cached one.
 */
export const fieldDefinitionsResponseSchema = z.object({
  module: z.string(),
  entity: z.string(),
  version: z.number().int(),
  sections: z.array(fieldSectionSchema),
});
export type FieldDefinitionsResponse = z.infer<typeof fieldDefinitionsResponseSchema>;
