import { z } from "zod";

/**
 * The 13 field types from docs/spec/Purchase-V2.md §4 ("client's own
 * definitions"). apps/web's schema-form field-type registry is keyed by
 * this enum — one component per value, never a switch outside the registry
 * (frontend rule 6). OPTIONAL on a field: the real field-engine (backend
 * prompt 11, apps/api/src/core/field-engine) only knows `dataType`, not
 * this richer UI-widget enum — apps/web derives a sensible fieldType from
 * dataType when it's absent (core/schema-form/resolve-field-type.ts). A
 * fixture that wants a type dataType can't express (Currency, Calculated,
 * Lookup, FileUpload, MultiUpload, AutoGenerated) sets fieldType directly.
 */
export const fieldTypeSchema = z.enum([
  "AutoGenerated",
  "Textbox",
  "TextArea",
  "Dropdown",
  "Lookup",
  "DatePicker",
  "Decimal",
  "Currency",
  "Percentage",
  "Toggle",
  "Calculated",
  "FileUpload",
  "MultiUpload",
]);
export type FieldType = z.infer<typeof fieldTypeSchema>;

/**
 * CLAUDE.md's field model. The real field-engine's GET /field-definitions
 * only ever resolves Tier 2 fields (backend prompt 11's explicit scope)
 * and sends the literal number `2` for it (core/field-engine/types.ts's
 * EffectiveField.tier), not this string enum - accept either; nothing in
 * apps/web currently branches on this value.
 */
export const fieldTierSchema = z.union([z.enum(["fixed", "configurable", "custom"]), z.number()]);
export type FieldTier = z.infer<typeof fieldTierSchema>;

/**
 * The primitive the value is validated/stored as, independent of the
 * widget (fieldType) that edits it. Mirrors apps/api/src/core/
 * field-engine/types.ts's FieldDataType exactly - not a value the frontend
 * gets to invent (this is real backend output, unlike fieldType).
 */
export const fieldDataTypeSchema = z.enum([
  "text",
  "textarea",
  "number",
  "decimal",
  "boolean",
  "date",
  "datetime",
  "select",
]);
export type FieldDataType = z.infer<typeof fieldDataTypeSchema>;

const optionsSourceObjectSchema = z.object({
  type: z.enum(["master", "enum", "static"]),
  master: z.string().optional(),
  dependsOn: z.string().optional(),
  staticOptions: z.array(z.object({ label: z.string(), value: z.string() })).optional(),
});

/**
 * Where a Dropdown/Lookup's options come from. The real field-engine sends
 * a bare string convention (e.g. "masters:countries" - core/masters/
 * registry.ts's cities.countryId field), not this richer object; parsed
 * into the same shape either way so every consumer (use-field-options.ts)
 * only ever handles one form. `dependsOn` (cascading - Country -> City per
 * the spec) has no backend equivalent yet since no field needs it: a
 * master's OWN cascading filter (e.g. cities by country) is a list-level
 * `parentValue` filter, not a form-field concern.
 */
export const optionsSourceSchema = z.union([z.string(), optionsSourceObjectSchema]).transform(
  (value): z.infer<typeof optionsSourceObjectSchema> => {
    if (typeof value !== "string") {
      return value;
    }
    // "roles" isn't a master (no core/masters/registry.ts entry - it's a
    // first-class RBAC concept, FE-5.5) but is options-sourced the same
    // way; use-field-options.ts routes master: "roles" to GET
    // /roles/options instead of /masters/roles/options.
    if (value === "roles") {
      return { type: "master", master: "roles" };
    }
    const [prefix, rest] = value.split(":");
    if (prefix === "masters" && rest) {
      return { type: "master", master: rest };
    }
    return { type: "static", staticOptions: [] };
  },
);
export type OptionsSource = z.infer<typeof optionsSourceObjectSchema>;

/** Simple show/hide-on-another-field's-value condition, e.g. `{ field: "through", operator: "eq", value: "sea" }`. No backend equivalent yet - set only by apps/web's own dev fixtures. */
export const visibilityConditionSchema = z.object({
  field: z.string(),
  operator: z.enum(["eq", "neq", "in", "notIn"]),
  value: z.union([z.string(), z.number(), z.boolean(), z.array(z.string())]),
});
export type VisibilityCondition = z.infer<typeof visibilityConditionSchema>;

/**
 * One resolved field: code-declared defaults already merged with the
 * company's field_definitions override and the requesting user's field
 * permissions (core/field-engine's job, server-side only — frontend rule
 * 4). Unlike a fixture built for FE-3's dev route, the REAL field-engine
 * does NOT omit an invisible field from the response - it sends
 * `isVisible: false` instead, so every consumer must check it (frontend
 * rule 4: this is metadata to obey, not a permission to re-derive).
 */
export const fieldDefinitionSchema = z.object({
  fieldKey: z.string(),
  tier: fieldTierSchema.optional(),
  label: z.string(),
  fieldType: fieldTypeSchema.optional(),
  dataType: fieldDataTypeSchema,
  isVisible: z.boolean().optional(),
  isMandatory: z.boolean(),
  isEditable: z.boolean(),
  isSystem: z.boolean(),
  sortOrder: z.number().int(),
  defaultValue: z.unknown().nullable().optional(),
  /** Dropdown only - a role picker etc. renders as a multi-select and stores an array, not a single string. No backend equivalent yet; set only by apps/web's own admin screens (modules/admin). */
  multiple: z.boolean().optional(),
  optionsSource: optionsSourceSchema.nullable().optional(),
  visibilityCondition: visibilityConditionSchema.nullable().optional(),
  validation: z.record(z.string(), z.unknown()).nullable().optional(),
});
export type FieldDefinition = z.infer<typeof fieldDefinitionSchema>;

/** A form section, e.g. "Purchase Header", "Shipment Details" — rendered as an AntD Card/Collapse per FE-3. No backend equivalent yet (the real endpoint returns a flat `fields` array - see fieldDefinitionsResponseSchema); apps/web's resolve-sections.ts wraps a flat response into one implicit section. */
export const fieldSectionSchema = z.object({
  key: z.string(),
  label: z.string(),
  sortOrder: z.number().int(),
  fields: z.array(fieldDefinitionSchema),
});
export type FieldSection = z.infer<typeof fieldSectionSchema>;

// --- GET /api/v1/field-definitions/:module/:entity -------------------------

/**
 * Two shapes coexist here: the REAL field-engine's flat `{module, entity,
 * fields}` (no `version`, no `sections` - apps/api/src/modules/
 * field-definitions/field-definitions.controller.ts) and FE-3's
 * section-grouped, versioned dev fixtures. apps/web/src/core/
 * field-definitions/resolve-sections.ts is the one place that reads
 * either; `version` drives compile-validator.ts's memoization when present
 * and is skipped (falls back to per-render memoization) when absent.
 */
export const fieldDefinitionsResponseSchema = z.object({
  module: z.string(),
  entity: z.string(),
  version: z.number().int().optional(),
  fields: z.array(fieldDefinitionSchema).optional(),
  sections: z.array(fieldSectionSchema).optional(),
});
export type FieldDefinitionsResponse = z.infer<typeof fieldDefinitionsResponseSchema>;
