import { z, type ZodTypeAny } from "zod";
import type { FieldDefinition, FieldDefinitionsResponse, FieldType } from "@hyperion/contracts";
import { NUMERIC_STRING_PATTERN } from "./numeric-string";
import { resolveFieldType } from "./resolve-field-type";
import { resolveFieldSections } from "../field-definitions/resolve-sections";

const uploadedFileSchema = z.object({ uid: z.string(), name: z.string() });

function textBuilder(field: FieldDefinition, mandatory: boolean): ZodTypeAny {
  return mandatory ? z.string().min(1, `${field.label} is required`) : z.string();
}

/** Decimal/Currency/Percentage stay strings end to end (frontend rule 3) - this validates SHAPE, never converts to a number. */
function numericStringBuilder(field: FieldDefinition, mandatory: boolean): ZodTypeAny {
  const validNumber = z.string().regex(NUMERIC_STRING_PATTERN, `${field.label} must be a valid number`);
  return mandatory ? validNumber.min(1, `${field.label} is required`) : z.union([z.literal(""), validNumber]);
}

function booleanBuilder(): ZodTypeAny {
  return z.boolean();
}

function readOnlyBuilder(): ZodTypeAny {
  return z.string().optional();
}

function fileBuilder(_field: FieldDefinition, mandatory: boolean): ZodTypeAny {
  return mandatory ? uploadedFileSchema : uploadedFileSchema.nullable();
}

function multiFileBuilder(field: FieldDefinition, mandatory: boolean): ZodTypeAny {
  const base = z.array(uploadedFileSchema);
  return mandatory ? base.min(1, `${field.label} is required`) : base;
}

type FieldSchemaBuilder = (field: FieldDefinition, mandatory: boolean) => ZodTypeAny;

/** One builder per field type - mirrors the render registry (field-types/registry.ts), not a switch, for the same reason (frontend rule 6). */
const builders: Record<FieldType, FieldSchemaBuilder> = {
  AutoGenerated: readOnlyBuilder,
  Textbox: textBuilder,
  TextArea: textBuilder,
  Dropdown: textBuilder,
  Lookup: textBuilder,
  DatePicker: textBuilder,
  Decimal: numericStringBuilder,
  Currency: numericStringBuilder,
  Percentage: numericStringBuilder,
  Toggle: booleanBuilder,
  Calculated: readOnlyBuilder,
  FileUpload: fileBuilder,
  MultiUpload: multiFileBuilder,
};

/** A non-editable or system-computed field can't be fixed by the user, so it's never treated as mandatory client-side - the value just round-trips whatever it already was. */
function isEffectivelyMandatory(field: FieldDefinition, fieldType: FieldType): boolean {
  return field.isMandatory && field.isEditable && fieldType !== "AutoGenerated" && fieldType !== "Calculated";
}

type CompiledSchema = z.ZodObject<Record<string, ZodTypeAny>>;

/**
 * field-definitions -> Zod schema at runtime, memoized by (module, entity,
 * version) when a version is present - mirrors what the backend does with
 * AJV so client and server validation cannot drift, and a
 * field_definition.changed event never serves a stale cached schema. The
 * real field-engine doesn't send a version at all (see
 * fieldDefinitionsResponseSchema's doc comment); without one this just
 * recompiles every call; callers already wrap this in useMemo keyed on
 * the query data, so that's a rare-render cost, not a rare-parse one.
 */
const cache = new Map<string, CompiledSchema>();

export function compileValidator(schema: FieldDefinitionsResponse): CompiledSchema {
  const cacheKey = schema.version !== undefined ? `${schema.module}:${schema.entity}:${schema.version}` : undefined;
  const cached = cacheKey ? cache.get(cacheKey) : undefined;
  if (cached) {
    return cached;
  }

  const shape: Record<string, ZodTypeAny> = {};
  for (const section of resolveFieldSections(schema)) {
    for (const field of section.fields) {
      const fieldType = resolveFieldType(field);
      shape[field.fieldKey] = builders[fieldType](field, isEffectivelyMandatory(field, fieldType));
    }
  }

  const compiled = z.object(shape);
  if (cacheKey) {
    cache.set(cacheKey, compiled);
  }
  return compiled;
}
