import type { FieldDefinitionsResponse, FieldType } from "@ikration/contracts";
import { resolveFieldSections } from "../field-definitions/resolve-sections";
import { resolveFieldType } from "./resolve-field-type";

const EMPTY_VALUE_BY_TYPE: Record<FieldType, unknown> = {
  AutoGenerated: "",
  Textbox: "",
  TextArea: "",
  Dropdown: "",
  Lookup: "",
  DatePicker: "",
  Decimal: "",
  Currency: "",
  Percentage: "",
  Toggle: false,
  Calculated: "",
  FileUpload: null,
  MultiUpload: [],
};

/** initialValues (edit/view) win, then the schema's own default_value, then a type-appropriate empty value - every field always has SOME value so inputs stay controlled from the first render. */
export function buildDefaultValues(
  schema: FieldDefinitionsResponse,
  initialValues: Record<string, unknown> | undefined,
): Record<string, unknown> {
  const values: Record<string, unknown> = {};

  for (const section of resolveFieldSections(schema)) {
    for (const field of section.fields) {
      const initialValue = initialValues?.[field.fieldKey];
      // A field the API returns as `null` (never filled in) must still fall
      // through to the type-appropriate empty value below, not be carried
      // through as literal `null` - compile-validator.ts's non-mandatory
      // Textbox/TextArea builder is `z.string()`, which rejects `null`,
      // turning a genuinely optional, blank field into an "Invalid input"
      // error on Save in edit mode only (create mode has no initialValues
      // at all, so this never surfaced there).
      if (initialValues && field.fieldKey in initialValues && initialValue !== null) {
        values[field.fieldKey] = initialValue;
      } else if (field.defaultValue !== undefined && field.defaultValue !== null) {
        values[field.fieldKey] = field.defaultValue;
      } else if (resolveFieldType(field) === "Dropdown" && field.multiple) {
        values[field.fieldKey] = [];
      } else {
        values[field.fieldKey] = EMPTY_VALUE_BY_TYPE[resolveFieldType(field)];
      }
    }
  }

  return values;
}
