import type { FieldDefinitionsResponse, FieldType } from "@hyperion/contracts";
import { resolveFieldSections } from "../field-definitions/resolve-sections";
import { resolveFieldType } from "./resolve-field-type";

const EMPTY_VALUE_BY_TYPE: Record<FieldType, unknown> = {
  AutoGenerated: "",
  Textbox: "",
  TextArea: "",
  Dropdown: "",
  Lookup: "",
  DatePicker: "",
  Decimal: "",
  Currency: "",
  Percentage: "",
  Toggle: false,
  Calculated: "",
  FileUpload: null,
  MultiUpload: [],
};

/** initialValues (edit/view) win, then the schema's own default_value, then a type-appropriate empty value - every field always has SOME value so inputs stay controlled from the first render. */
export function buildDefaultValues(
  schema: FieldDefinitionsResponse,
  initialValues: Record<string, unknown> | undefined,
): Record<string, unknown> {
  const values: Record<string, unknown> = {};

  for (const section of resolveFieldSections(schema)) {
    for (const field of section.fields) {
      if (initialValues && field.fieldKey in initialValues) {
        values[field.fieldKey] = initialValues[field.fieldKey];
      } else if (field.defaultValue !== undefined && field.defaultValue !== null) {
        values[field.fieldKey] = field.defaultValue;
      } else if (resolveFieldType(field) === "Dropdown" && field.multiple) {
        values[field.fieldKey] = [];
      } else {
        values[field.fieldKey] = EMPTY_VALUE_BY_TYPE[resolveFieldType(field)];
      }
    }
  }

  return values;
}
