import type { ReactElement } from "react";
import { useWatch, type Control } from "react-hook-form";
import type { FieldDefinition } from "@hyperion/contracts";
import { fieldTypeRegistry } from "./field-types/registry";
import { evaluateVisibility } from "./visibility";
import type { SchemaFormMode } from "./types";

const NO_VISIBILITY_DEPENDENCY = "__schema_form_no_visibility_dependency__";

export function FieldRenderer({
  field,
  control,
  mode,
}: {
  field: FieldDefinition;
  control: Control<Record<string, unknown>>;
  mode: SchemaFormMode;
}): ReactElement | null {
  const watchedValue = useWatch({
    control,
    name: field.visibilityCondition?.field ?? NO_VISIBILITY_DEPENDENCY,
  });

  if (field.visibilityCondition && !evaluateVisibility(watchedValue, field.visibilityCondition)) {
    return null;
  }

  const Component = fieldTypeRegistry[field.fieldType];
  const readOnly =
    mode === "view" ||
    !field.isEditable ||
    field.fieldType === "AutoGenerated" ||
    field.fieldType === "Calculated";

  return <Component field={field} control={control} readOnly={readOnly} />;
}
