import type { ReactElement } from "react";
import { useWatch, type Control } from "react-hook-form";
import type { FieldDefinition, FieldType } from "@ikration/contracts";
import { fieldTypeRegistry } from "./field-types/registry";
import { evaluateVisibility } from "./visibility";
import { resolveFieldType } from "./resolve-field-type";
import type { UploadContext } from "./field-types/types";
import type { SchemaFormMode } from "./types";

const NO_VISIBILITY_DEPENDENCY = "__schema_form_no_visibility_dependency__";

/** Multi-line text needs real horizontal room to be readable - a single-file/multi-file upload is just a button, so it shares the section's grid columns like everything else (forcing it full-width left each upload on its own mostly-empty row). */
const FULL_WIDTH_FIELD_TYPES = new Set<FieldType>(["TextArea"]);

export function FieldRenderer({
  field,
  control,
  mode,
  uploadContext,
}: {
  field: FieldDefinition;
  control: Control<Record<string, unknown>>;
  mode: SchemaFormMode;
  uploadContext: UploadContext | undefined;
}): ReactElement | null {
  const watchedValue = useWatch({
    control,
    name: field.visibilityCondition?.field ?? NO_VISIBILITY_DEPENDENCY,
  });

  if (field.visibilityCondition && !evaluateVisibility(watchedValue, field.visibilityCondition)) {
    return null;
  }

  const fieldType = resolveFieldType(field);
  const Component = fieldTypeRegistry[fieldType];
  const readOnly =
    mode === "view" || !field.isEditable || fieldType === "AutoGenerated" || fieldType === "Calculated";

  // The wrapper (not just the field component) is what a hidden field must
  // skip entirely - an empty grid cell here would leave a visible gap in
  // SchemaForm.tsx's .field-grid.
  return (
    <div className={FULL_WIDTH_FIELD_TYPES.has(fieldType) ? "field-grid-item field-grid-item--full" : "field-grid-item"}>
      <Component field={field} control={control} readOnly={readOnly} {...(uploadContext ? { uploadContext } : {})} />
    </div>
  );
}
