import { act } from "react";
import { describe, expect, it, vi } from "vitest";
import { http, HttpResponse } from "msw";
import userEvent from "@testing-library/user-event";
import { screen, waitFor } from "@testing-library/react";
import type { FieldDefinition, FieldDefinitionsResponse } from "@hyperion/contracts";
import { server } from "../../mocks/server";
import { queryClient } from "../api/query-client";
import { endpoints } from "../api/endpoints";
import { renderWithProviders } from "../../test/render-with-providers";
import { SchemaForm } from "./SchemaForm";
import { schemaFormDevFixture } from "./dev-fixture";

const API_BASE = import.meta.env.VITE_API_BASE_URL;

function mockFieldDefinitions(module: string, entity: string, response: FieldDefinitionsResponse): void {
  server.use(http.get(`${API_BASE}${endpoints.fieldDefinitions(module, entity)}`, () => HttpResponse.json(response)));
}

function field(
  overrides: Partial<FieldDefinition> & Pick<FieldDefinition, "fieldKey" | "label" | "fieldType">,
): FieldDefinition {
  return {
    tier: "fixed",
    dataType: "text",
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 1,
    ...overrides,
  };
}

function buildFixture(
  module: string,
  entity: string,
  version: number,
  fields: FieldDefinition[],
): FieldDefinitionsResponse {
  return { module, entity, version, sections: [{ key: "section", label: "Section", sortOrder: 1, fields }] };
}

describe("SchemaForm - all 13 field types", () => {
  it("renders every field type from the dev fixture and round-trips a value for each", async () => {
    mockFieldDefinitions(schemaFormDevFixture.module, schemaFormDevFixture.entity, schemaFormDevFixture);
    const onSubmit = vi.fn();
    const user = userEvent.setup();

    renderWithProviders(
      <SchemaForm module={schemaFormDevFixture.module} entity={schemaFormDevFixture.entity} mode="create" onSubmit={onSubmit} />,
    );

    // AutoGenerated - read-only, empty placeholder before save
    expect(await screen.findByText("Generated on save")).toBeInTheDocument();

    // Visibility: Vessel Name is hidden until Through = Sea
    expect(screen.queryByLabelText("Vessel Name")).not.toBeInTheDocument();

    // Textbox / TextArea / Toggle
    await user.type(screen.getByLabelText("Short Name"), "ACME Corp");
    await user.type(screen.getByLabelText("Remarks"), "Handled with care");
    await user.click(screen.getByRole("switch", { name: "Active" }));

    // Cascading Dropdown: City is disabled until Country is chosen
    const citySelect = screen.getByRole("combobox", { name: "City" });
    expect(citySelect).toBeDisabled();

    await user.click(screen.getByRole("combobox", { name: "Country" }));
    await user.click(await screen.findByText("United Arab Emirates"));

    await waitFor(() => expect(citySelect).not.toBeDisabled());
    await user.click(citySelect);
    await user.click(await screen.findByText("Dubai"));

    // Lookup: searchable
    await user.click(screen.getByRole("combobox", { name: "Warehouse" }));
    await user.type(screen.getByRole("combobox", { name: "Warehouse" }), "Jebel");
    await user.click(await screen.findByText("Jebel Ali Warehouse"));

    // DatePicker - value round-trips as a plain ISO string
    const dateInput = screen.getByLabelText("Loading Date");
    await user.click(dateInput);
    await user.type(dateInput, "2026-08-01");
    await user.keyboard("{Enter}");

    // Decimal / Currency / Percentage - strings, never InputNumber
    await user.type(screen.getByLabelText("Quantity"), "500");
    await user.type(screen.getByLabelText("Purchase Rate (USD)"), "8432.75");
    await user.type(screen.getByLabelText("Agreed Premium"), "2.35");

    // Calculated - always read-only, shows the server-provided value
    expect(screen.getByText("8632.19")).toBeInTheDocument();

    // Dropdown (enum) drives visibility for Vessel Name
    await user.click(screen.getByRole("combobox", { name: "Through" }));
    await user.click(await screen.findByText("Sea"));
    await user.type(await screen.findByLabelText("Vessel Name"), "MV Test Vessel");

    // FileUpload / MultiUpload
    await user.upload(
      screen.getByLabelText("Invoice"),
      new File(["invoice-bytes"], "invoice.pdf", { type: "application/pdf" }),
    );
    await user.upload(screen.getByLabelText("Other Documents"), [
      new File(["a"], "packing-list.pdf", { type: "application/pdf" }),
      new File(["b"], "coo.pdf", { type: "application/pdf" }),
    ]);

    await user.click(screen.getByRole("button", { name: "Save" }));

    await waitFor(() => expect(onSubmit).toHaveBeenCalledTimes(1));
    const payload = onSubmit.mock.calls[0]?.[0] as Record<string, unknown>;

    expect(payload.shortName).toBe("ACME Corp");
    expect(payload.remarks).toBe("Handled with care");
    expect(payload.isActive).toBe(true);
    expect(payload.country).toBe("ae");
    expect(payload.city).toBe("dubai");
    expect(payload.warehouse).toBe("wh-1");
    expect(payload.loadingDate).toBe("2026-08-01");
    expect(payload.quantity).toBe("500");
    expect(payload.purchaseRateUsd).toBe("8432.75");
    expect(payload.agreedPremiumPct).toBe("2.35");
    expect(payload.finalPurchaseRateUsd).toBe("8632.19");
    expect(payload.through).toBe("sea");
    expect(payload.vesselName).toBe("MV Test Vessel");
    expect(payload.invoice).toMatchObject({ name: "invoice.pdf" });
    expect(payload.otherDocuments).toHaveLength(2);

    // The money assertion that matters: never a float, always a string.
    expect(typeof payload.quantity).toBe("string");
    expect(typeof payload.purchaseRateUsd).toBe("string");
    expect(typeof payload.agreedPremiumPct).toBe("string");
    expect(typeof payload.finalPurchaseRateUsd).toBe("string");
  }, 20000);
});

describe("SchemaForm - metadata-driven rendering", () => {
  it("renders the label ONLY from metadata - changing it in the schema changes the DOM", async () => {
    const module = "_dev";
    const entity = "label-metadata-test";
    const nameField = field({ fieldKey: "name", label: "Original Label", fieldType: "Textbox" });
    const fixture = buildFixture(module, entity, 1, [nameField]);
    mockFieldDefinitions(module, entity, fixture);

    renderWithProviders(<SchemaForm module={module} entity={entity} mode="create" onSubmit={vi.fn()} />);
    expect(await screen.findByLabelText("Original Label")).toBeInTheDocument();

    const relabeled = buildFixture(module, entity, 1, [{ ...nameField, label: "Renamed Label" }]);
    act(() => {
      queryClient.setQueryData(["field-definitions", module, entity], relabeled);
    });

    expect(await screen.findByLabelText("Renamed Label")).toBeInTheDocument();
    expect(screen.queryByLabelText("Original Label")).not.toBeInTheDocument();
  });

  it("fires validation from the mandatory flag in metadata and blocks submission", async () => {
    const module = "_dev";
    const entity = "mandatory-test";
    const fixture = buildFixture(module, entity, 1, [
      field({ fieldKey: "name", label: "Name", fieldType: "Textbox", isMandatory: true }),
    ]);
    mockFieldDefinitions(module, entity, fixture);
    const onSubmit = vi.fn();
    const user = userEvent.setup();

    renderWithProviders(<SchemaForm module={module} entity={entity} mode="create" onSubmit={onSubmit} />);
    await screen.findByLabelText("Name");

    await user.click(screen.getByRole("button", { name: "Save" }));

    expect(await screen.findByText("Name is required")).toBeInTheDocument();
    expect(onSubmit).not.toHaveBeenCalled();
  });

  it("does not render a field the schema omits", async () => {
    const module = "_dev";
    const entity = "omitted-field-test";
    const fixture = buildFixture(module, entity, 1, [
      field({ fieldKey: "keptField", label: "Kept Field", fieldType: "Textbox" }),
    ]);
    mockFieldDefinitions(module, entity, fixture);

    renderWithProviders(<SchemaForm module={module} entity={entity} mode="create" onSubmit={vi.fn()} />);

    expect(await screen.findByLabelText("Kept Field")).toBeInTheDocument();
    expect(screen.queryByText("Omitted Field")).not.toBeInTheDocument();
  });

  it("renders a non-editable field read-only and its value passes through unchanged on submit", async () => {
    const module = "_dev";
    const entity = "read-only-test";
    const fixture = buildFixture(module, entity, 1, [
      field({
        fieldKey: "code",
        label: "Code",
        fieldType: "Textbox",
        isEditable: false,
        defaultValue: "FIXED-001",
      }),
    ]);
    mockFieldDefinitions(module, entity, fixture);
    const onSubmit = vi.fn();
    const user = userEvent.setup();

    renderWithProviders(<SchemaForm module={module} entity={entity} mode="create" onSubmit={onSubmit} />);

    expect(await screen.findByText("FIXED-001")).toBeInTheDocument();
    expect(screen.queryByRole("textbox", { name: "Code" })).not.toBeInTheDocument();

    await user.click(screen.getByRole("button", { name: "Save" }));
    await waitFor(() => expect(onSubmit).toHaveBeenCalledWith({ code: "FIXED-001" }));
  });
});

describe("SchemaForm - money as strings", () => {
  it("never produces a float for Decimal/Currency/Percentage - submitted payload stays a string", async () => {
    const module = "_dev";
    const entity = "money-test";
    const fixture = buildFixture(module, entity, 1, [
      field({ fieldKey: "quantity", label: "Quantity", fieldType: "Decimal", isMandatory: true }),
      field({ fieldKey: "rateUsd", label: "Rate (USD)", fieldType: "Currency", isMandatory: true }),
      field({ fieldKey: "premiumPct", label: "Premium", fieldType: "Percentage", isMandatory: true }),
    ]);
    mockFieldDefinitions(module, entity, fixture);
    const onSubmit = vi.fn();
    const user = userEvent.setup();

    renderWithProviders(<SchemaForm module={module} entity={entity} mode="create" onSubmit={onSubmit} />);
    await screen.findByLabelText("Quantity");

    // Letters and a second decimal point are rejected keystroke-by-keystroke - never silently coerced.
    const quantityInput = screen.getByLabelText("Quantity");
    await user.type(quantityInput, "12a.5.6b");
    expect(quantityInput).toHaveValue("12.56");

    await user.clear(quantityInput);
    await user.type(quantityInput, "500.5");
    await user.type(screen.getByLabelText("Rate (USD)"), "8432.75");
    await user.type(screen.getByLabelText("Premium"), "2.35");

    await user.click(screen.getByRole("button", { name: "Save" }));

    await waitFor(() => expect(onSubmit).toHaveBeenCalledTimes(1));
    const payload = onSubmit.mock.calls[0]?.[0] as Record<string, unknown>;

    expect(payload).toEqual({ quantity: "500.5", rateUsd: "8432.75", premiumPct: "2.35" });
    expect(typeof payload.quantity).toBe("string");
    expect(typeof payload.rateUsd).toBe("string");
    expect(typeof payload.premiumPct).toBe("string");
  });
});

describe("SchemaForm - cascading dropdowns", () => {
  it("filters City options by the selected Country, and resets City when Country changes", async () => {
    const module = "_dev";
    const entity = "cascade-test";
    const fixture = buildFixture(module, entity, 1, [
      field({
        fieldKey: "country",
        label: "Country",
        fieldType: "Dropdown",
        isMandatory: true,
        optionsSource: { type: "master", master: "countries" },
      }),
      field({
        fieldKey: "city",
        label: "City",
        fieldType: "Dropdown",
        optionsSource: { type: "master", master: "cities", dependsOn: "country" },
      }),
    ]);
    mockFieldDefinitions(module, entity, fixture);
    const user = userEvent.setup();

    renderWithProviders(<SchemaForm module={module} entity={entity} mode="create" onSubmit={vi.fn()} />);

    const citySelect = await screen.findByRole("combobox", { name: "City" });
    expect(citySelect).toBeDisabled();

    await user.click(screen.getByRole("combobox", { name: "Country" }));
    await user.click(await screen.findByText("United Arab Emirates"));
    await waitFor(() => expect(citySelect).not.toBeDisabled());

    await user.click(citySelect);
    expect(await screen.findByText("Dubai")).toBeInTheDocument();
    expect(await screen.findByText("Abu Dhabi")).toBeInTheDocument();
    expect(screen.queryByText("Mumbai")).not.toBeInTheDocument();

    await user.click(screen.getByText("Dubai"));
    // The (still-mounted-but-hidden) dropdown option and the selected-value
    // chip both render "Dubai" once selected - only the chip has this class.
    const selectedChip = { selector: ".ant-select-selection-item" };
    expect(screen.getByText("Dubai", selectedChip)).toBeInTheDocument();

    // Changing the parent clears the now-invalid child selection.
    await user.click(screen.getByRole("combobox", { name: "Country" }));
    await user.click(await screen.findByText("India"));

    await waitFor(() => expect(screen.queryByText("Dubai", selectedChip)).not.toBeInTheDocument());
    await user.click(screen.getByRole("combobox", { name: "City" }));
    expect(await screen.findByText("Mumbai")).toBeInTheDocument();
    expect(screen.queryByText("Dubai")).not.toBeInTheDocument();
  });
});
