import type { ReactElement, ReactNode } from "react";
import { useMemo, useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useQuery } from "@tanstack/react-query";
import { Alert, Button, Card, Space, Spin, Form as AntForm } from "antd";
import { fieldDefinitionsResponseSchema, type FieldDefinitionsResponse } from "@ikration/contracts";
import { apiFetch } from "../api/client";
import { endpoints } from "../api/endpoints";
import { notifyError, toToastPayload } from "../api/error-toast";
import { compileValidator } from "./compile-validator";
import { buildDefaultValues } from "./default-values";
import { FieldRenderer } from "./FieldRenderer";
import { resolveFieldType } from "./resolve-field-type";
import type { SchemaFormMode } from "./types";
import type { UploadContext } from "./field-types/types";
import { resolveFieldSections } from "../field-definitions/resolve-sections";

export type { SchemaFormMode } from "./types";

/**
 * AutoGenerated (e.g. a Supplier Code) never has a real value before the
 * server assigns one - react-hook-form still carries its "" default in
 * `values`, and a create endpoint's schema is .strict() and never declares
 * that key at all, so submitting it (even as "") is rejected outright
 * rather than ignored. Calculated fields are NOT stripped here: unlike
 * AutoGenerated, they carry a real client-computed value (e.g.
 * finalPurchaseRateUsd) the backend expects to receive - `isSystem &&
 * !isEditable` alone can't tell the two apart (both set it), so this
 * relies on core/field-engine/defaults.ts actually declaring
 * fieldType: "AutoGenerated" on server-generated fields.
 */
function stripServerOwnedFields(
  schema: FieldDefinitionsResponse,
  values: Record<string, unknown>,
): Record<string, unknown> {
  const autoGeneratedKeys = new Set<string>();
  for (const section of resolveFieldSections(schema)) {
    for (const field of section.fields) {
      if (resolveFieldType(field) === "AutoGenerated") {
        autoGeneratedKeys.add(field.fieldKey);
      }
    }
  }
  return Object.fromEntries(Object.entries(values).filter(([key]) => !autoGeneratedKeys.has(key)));
}

/**
 * An untouched optional field defaults to "" (default-values.ts's
 * EMPTY_VALUE_BY_TYPE) so every input stays controlled from first render -
 * but "" is not the same as "not provided" to a `.optional()` Zod schema
 * server-side: `z.string().min(1).optional()` rejects an empty string
 * outright (only a genuinely absent key satisfies "optional"), and
 * `z.string().uuid().optional()` rejects "" as an invalid UUID the same
 * way. The compiled client validator (compile-validator.ts) never blocks
 * submission on this - a non-mandatory field's builder always allows ""
 * through - so without this, leaving ANY optional field blank (a
 * Textarea, an unselected Dropdown/Lookup) 422s a create/update that
 * should have succeeded. Mandatory fields can never reach here as "" (the
 * compiled validator already blocks submission before onSubmit fires), so
 * this only ever drops keys a mandatory field could never have held.
 */
function stripEmptyOptionalFields(
  schema: FieldDefinitionsResponse,
  values: Record<string, unknown>,
): Record<string, unknown> {
  const optionalKeys = new Set<string>();
  for (const section of resolveFieldSections(schema)) {
    for (const field of section.fields) {
      if (!field.isMandatory) {
        optionalKeys.add(field.fieldKey);
      }
    }
  }
  return Object.fromEntries(
    Object.entries(values).filter(([key, value]) => !(optionalKeys.has(key) && value === "")),
  );
}

export interface SchemaFormProps {
  module: string;
  entity: string;
  mode: SchemaFormMode;
  initialValues?: Record<string, unknown>;
  onSubmit: (values: Record<string, unknown>) => void | Promise<void>;
  /** FileUpload/MultiUpload fields need a real entity/entityId to attach to - absent (e.g. create mode, before the record has an id) they fall back to local-only tracking. */
  uploadContext?: UploadContext;
  /**
   * Field keys to drop entirely (not merely hidden) before validating and
   * rendering - for a field whose applicability depends on OTHER data the
   * static field-definitions schema can't see (e.g. purchase/item's
   * purchaseRateUsd is server-rejected under a purchase's pricing_type
   * "lme" - purchase-items.service.ts derives it from the LME record
   * instead). Still schema-driven (frontend rule 1): the caller names
   * which key to drop, never a label/type/layout of its own.
   */
  hiddenFields?: string[];
  /**
   * Content rendered inside this SAME form, after the field-definitions
   * sections but before the one Save button - for a caller that has its
   * own non-field-definitions sub-editor bolted onto this entity (e.g.
   * Supplier's contacts/banks sub-tables, FE-6 - there's no repeating-
   * group field type in the 13-type spec, so these can't be schema-driven
   * fields). Rendering them as a sibling AFTER SchemaForm instead strands
   * them after the Save button, looking like they have no way to commit
   * even though the caller's onSubmit merges their state in regardless.
   * The caller owns whatever state/onChange this content needs; SchemaForm
   * only renders it.
   */
  footer?: ReactNode;
}

/**
 * THE core bet of the project (FE-3): every form in this ERP renders
 * through this component. It fetches the field-definitions schema, compiles
 * it to a Zod validator, and renders sections/fields entirely from that
 * metadata - order, labels, mandatory, visibility, editability. It never
 * decides what to show; the backend already intersected definitions with
 * the caller's field permissions (frontend rule 4).
 */
export function SchemaForm({
  module,
  entity,
  mode,
  initialValues,
  onSubmit,
  uploadContext,
  hiddenFields,
  footer,
}: SchemaFormProps): ReactElement {
  const schemaQuery = useQuery({
    queryKey: ["field-definitions", module, entity],
    queryFn: () =>
      apiFetch(endpoints.fieldDefinitions(module, entity), {}, { schema: fieldDefinitionsResponseSchema }),
  });

  if (schemaQuery.isLoading) {
    return <Spin data-testid="schema-form-loading" />;
  }

  if (schemaQuery.isError || !schemaQuery.data) {
    return <Alert type="error" showIcon message="Could not load the form definition" />;
  }

  const schema: FieldDefinitionsResponse = hiddenFields?.length
    ? { ...schemaQuery.data, fields: schemaQuery.data.fields?.filter((field) => !hiddenFields.includes(field.fieldKey)) }
    : schemaQuery.data;

  return (
    <SchemaFormBody
      schema={schema}
      mode={mode}
      initialValues={initialValues}
      onSubmit={onSubmit}
      uploadContext={uploadContext}
      footer={footer}
    />
  );
}

function SchemaFormBody({
  schema,
  mode,
  initialValues,
  onSubmit,
  uploadContext,
  footer,
}: {
  schema: FieldDefinitionsResponse;
  mode: SchemaFormMode;
  initialValues: Record<string, unknown> | undefined;
  onSubmit: (values: Record<string, unknown>) => void | Promise<void>;
  uploadContext: UploadContext | undefined;
  footer: ReactNode;
}): ReactElement {
  const validator = useMemo(() => compileValidator(schema), [schema]);
  const defaultValues = useMemo(
    () => buildDefaultValues(schema, initialValues),
    // initialValues is re-created per render at most call sites; the schema
    // (module/entity/version) is the thing that should actually drive a reset.
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [schema],
  );

  const { control, handleSubmit } = useForm<Record<string, unknown>>({
    resolver: zodResolver(validator),
    defaultValues,
  });
  const [submitError, setSubmitError] = useState<string | null>(null);

  const submit = handleSubmit(async (values) => {
    setSubmitError(null);
    try {
      await onSubmit(stripEmptyOptionalFields(schema, stripServerOwnedFields(schema, values)));
    } catch (error) {
      // A plain async handler, not a useMutation - `void submit()` below
      // would otherwise discard the rejection outright and a thrown
      // ApiError (e.g. BE-7's 403 on an approval-holding provisioned role)
      // would never reach the user. Same payload shape as the global toast
      // (query-client.ts), so both channels agree on the same message.
      const payload = toToastPayload(error);
      notifyError(payload);
      setSubmitError(payload.description ?? payload.message);
    }
  });

  const sections = resolveFieldSections(schema);

  return (
    <AntForm layout="vertical" onFinish={() => void submit()}>
      <Space direction="vertical" size="middle" style={{ width: "100%" }}>
        {sections.map((section) => (
          <Card key={section.key} title={section.label || undefined} size="small">
            {section.fields.map((field) => (
              <FieldRenderer key={field.fieldKey} field={field} control={control} mode={mode} uploadContext={uploadContext} />
            ))}
          </Card>
        ))}
        {footer}
        {submitError && <Alert type="error" showIcon message={submitError} />}
        {mode !== "view" && (
          <Button type="primary" htmlType="submit">
            Save
          </Button>
        )}
      </Space>
    </AntForm>
  );
}
