import type { ReactElement, ReactNode } from "react";
import { useMemo, useState } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useQuery } from "@tanstack/react-query";
import { Alert, Button, Card, ConfigProvider, Popconfirm, Space, Spin, Typography, Form as AntForm } from "antd";
import { fieldDefinitionsResponseSchema, type FieldDefinitionsResponse } from "@ikration/contracts";
import { apiFetch } from "../api/client";
import { endpoints } from "../api/endpoints";
import { notifyError, toToastPayload } from "../api/error-toast";
import { compileValidator } from "./compile-validator";
import { buildDefaultValues } from "./default-values";
import { FieldRenderer } from "./FieldRenderer";
import { resolveFieldType } from "./resolve-field-type";
import type { SchemaFormMode } from "./types";
import type { UploadContext } from "./field-types/types";
import { resolveFieldSections } from "../field-definitions/resolve-sections";

export type { SchemaFormMode } from "./types";

/**
 * AutoGenerated (e.g. a Supplier Code) never has a real value before the
 * server assigns one - react-hook-form still carries its "" default in
 * `values`, and a create endpoint's schema is .strict() and never declares
 * that key at all, so submitting it (even as "") is rejected outright
 * rather than ignored. Calculated fields are NOT stripped here: unlike
 * AutoGenerated, they carry a real client-computed value (e.g.
 * finalPurchaseRateUsd) the backend expects to receive - `isSystem &&
 * !isEditable` alone can't tell the two apart (both set it), so this
 * relies on core/field-engine/defaults.ts actually declaring
 * fieldType: "AutoGenerated" on server-generated fields.
 */
function stripServerOwnedFields(
  schema: FieldDefinitionsResponse,
  values: Record<string, unknown>,
): Record<string, unknown> {
  const autoGeneratedKeys = new Set<string>();
  for (const section of resolveFieldSections(schema)) {
    for (const field of section.fields) {
      if (resolveFieldType(field) === "AutoGenerated") {
        autoGeneratedKeys.add(field.fieldKey);
      }
    }
  }
  return Object.fromEntries(Object.entries(values).filter(([key]) => !autoGeneratedKeys.has(key)));
}

/**
 * FileUpload/MultiUpload fields track a value locally (or via a real
 * upload to `/attachments/:entity/:entityId/:fieldKey`, FileUploadField's
 * own `uploadContext` path) purely so the widget has something to render -
 * that value was never meant to travel through THIS form's own
 * create/update body. Every `.strict()` backend schema (createPurchaseSchema,
 * createPurchaseInvoiceSchema, ...) deliberately never declares these
 * keys - attachments go through their own API, always - so an untouched
 * field (`null`/`[]`, not caught by stripEmptyOptionalFields's `=== ""`
 * check) OR a genuinely-selected one would otherwise 422 the whole
 * submission on an "Unrecognized key" error.
 */
function stripUploadFields(
  schema: FieldDefinitionsResponse,
  values: Record<string, unknown>,
): Record<string, unknown> {
  const uploadKeys = new Set<string>();
  for (const section of resolveFieldSections(schema)) {
    for (const field of section.fields) {
      const fieldType = resolveFieldType(field);
      if (fieldType === "FileUpload" || fieldType === "MultiUpload") {
        uploadKeys.add(field.fieldKey);
      }
    }
  }
  return Object.fromEntries(Object.entries(values).filter(([key]) => !uploadKeys.has(key)));
}

/**
 * An untouched optional field defaults to "" (default-values.ts's
 * EMPTY_VALUE_BY_TYPE) so every input stays controlled from first render -
 * but "" is not the same as "not provided" to a `.optional()` Zod schema
 * server-side: `z.string().min(1).optional()` rejects an empty string
 * outright (only a genuinely absent key satisfies "optional"), and
 * `z.string().uuid().optional()` rejects "" as an invalid UUID the same
 * way. The compiled client validator (compile-validator.ts) never blocks
 * submission on this - a non-mandatory field's builder always allows ""
 * through - so without this, leaving ANY optional field blank (a
 * Textarea, an unselected Dropdown/Lookup) 422s a create/update that
 * should have succeeded. Mandatory fields can never reach here as "" (the
 * compiled validator already blocks submission before onSubmit fires), so
 * this only ever drops keys a mandatory field could never have held.
 */
function stripEmptyOptionalFields(
  schema: FieldDefinitionsResponse,
  values: Record<string, unknown>,
): Record<string, unknown> {
  const optionalKeys = new Set<string>();
  for (const section of resolveFieldSections(schema)) {
    for (const field of section.fields) {
      if (!field.isMandatory) {
        optionalKeys.add(field.fieldKey);
      }
    }
  }
  return Object.fromEntries(
    Object.entries(values).filter(([key, value]) => !(optionalKeys.has(key) && value === "")),
  );
}

export interface SchemaFormProps {
  module: string;
  entity: string;
  mode: SchemaFormMode;
  initialValues?: Record<string, unknown>;
  onSubmit: (values: Record<string, unknown>) => void | Promise<void>;
  /** FileUpload/MultiUpload fields need a real entity/entityId to attach to - absent (e.g. create mode, before the record has an id) they fall back to local-only tracking. */
  uploadContext?: UploadContext;
  /**
   * Field keys to drop entirely (not merely hidden) before validating and
   * rendering - for a field whose applicability depends on OTHER data the
   * static field-definitions schema can't see (e.g. purchase/item's
   * purchaseRateUsd is server-rejected under a purchase's pricing_type
   * "lme" - purchase-items.service.ts derives it from the LME record
   * instead). Still schema-driven (frontend rule 1): the caller names
   * which key to drop, never a label/type/layout of its own.
   */
  hiddenFields?: string[];
  /**
   * Content rendered inside this SAME form, after the field-definitions
   * sections but before the one Save button - for a caller that has its
   * own non-field-definitions sub-editor bolted onto this entity (e.g.
   * Supplier's contacts/banks sub-tables, FE-6 - there's no repeating-
   * group field type in the 13-type spec, so these can't be schema-driven
   * fields). Rendering them as a sibling AFTER SchemaForm instead strands
   * them after the Save button, looking like they have no way to commit
   * even though the caller's onSubmit merges their state in regardless.
   * The caller owns whatever state/onChange this content needs; SchemaForm
   * only renders it.
   */
  footer?: ReactNode;
  /**
   * Renders a "Discard" button beside Save (behind a confirm, since it can
   * throw away typed input) when provided - omitted entirely otherwise, so
   * a caller with nothing sensible to discard to (no `onDiscard` at all)
   * keeps today's Save-only bar. SchemaForm has no navigation/reset opinion
   * of its own - the caller decides what "discard" means (e.g. Purchase
   * navigates back to the list).
   */
  onDiscard?: () => void;
}

/**
 * THE core bet of the project (FE-3): every form in this ERP renders
 * through this component. It fetches the field-definitions schema, compiles
 * it to a Zod validator, and renders sections/fields entirely from that
 * metadata - order, labels, mandatory, visibility, editability. It never
 * decides what to show; the backend already intersected definitions with
 * the caller's field permissions (frontend rule 4).
 */
export function SchemaForm({
  module,
  entity,
  mode,
  initialValues,
  onSubmit,
  uploadContext,
  hiddenFields,
  footer,
  onDiscard,
}: SchemaFormProps): ReactElement {
  const schemaQuery = useQuery({
    queryKey: ["field-definitions", module, entity],
    queryFn: () =>
      apiFetch(endpoints.fieldDefinitions(module, entity), {}, { schema: fieldDefinitionsResponseSchema }),
  });

  if (schemaQuery.isLoading) {
    return <Spin data-testid="schema-form-loading" />;
  }

  if (schemaQuery.isError || !schemaQuery.data) {
    return <Alert type="error" showIcon message="Could not load the form definition" />;
  }

  const schema: FieldDefinitionsResponse = hiddenFields?.length
    ? { ...schemaQuery.data, fields: schemaQuery.data.fields?.filter((field) => !hiddenFields.includes(field.fieldKey)) }
    : schemaQuery.data;

  return (
    <SchemaFormBody
      schema={schema}
      mode={mode}
      initialValues={initialValues}
      onSubmit={onSubmit}
      uploadContext={uploadContext}
      footer={footer}
      onDiscard={onDiscard}
    />
  );
}

function SchemaFormBody({
  schema,
  mode,
  initialValues,
  onSubmit,
  uploadContext,
  footer,
  onDiscard,
}: {
  schema: FieldDefinitionsResponse;
  mode: SchemaFormMode;
  initialValues: Record<string, unknown> | undefined;
  onSubmit: (values: Record<string, unknown>) => void | Promise<void>;
  uploadContext: UploadContext | undefined;
  footer: ReactNode;
  onDiscard: (() => void) | undefined;
}): ReactElement {
  const validator = useMemo(() => compileValidator(schema), [schema]);
  const defaultValues = useMemo(
    () => buildDefaultValues(schema, initialValues),
    // initialValues is re-created per render at most call sites; the schema
    // (module/entity/version) is the thing that should actually drive a reset.
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [schema],
  );

  const { control, handleSubmit } = useForm<Record<string, unknown>>({
    resolver: zodResolver(validator),
    defaultValues,
  });
  const [submitError, setSubmitError] = useState<string | null>(null);

  const submit = handleSubmit(async (values) => {
    setSubmitError(null);
    try {
      await onSubmit(stripEmptyOptionalFields(schema, stripServerOwnedFields(schema, stripUploadFields(schema, values))));
    } catch (error) {
      // A plain async handler, not a useMutation - `void submit()` below
      // would otherwise discard the rejection outright and a thrown
      // ApiError (e.g. BE-7's 403 on an approval-holding provisioned role)
      // would never reach the user. Same payload shape as the global toast
      // (query-client.ts), so both channels agree on the same message.
      const payload = toToastPayload(error);
      notifyError(payload);
      setSubmitError(payload.description ?? payload.message);
    }
  });

  const sections = resolveFieldSections(schema);

  return (
    <AntForm layout="vertical" onFinish={() => void submit()}>
      <Space direction="vertical" size="large" style={{ width: "100%" }}>
        {/* Read/typed into, not scanned like a table - opts into the app's
            larger control size (controlHeightLG) instead of the dense
            default, scoped to just the field grid so `footer` (a caller's
            own sub-tables, e.g. Supplier's contacts/banks) keeps the
            app-wide density. ConfigProvider renders no DOM element of its
            own (a Context wrapper only) - one per Card, not one around the
            whole .map(), so each section stays its own item for Space's
            gap to apply between when an entity has more than one section. */}
        {sections.map((section) => (
          <ConfigProvider key={section.key} componentSize="large">
            {/* Borderless (no visible surface) for the common case: a flat
                response wrapped into one unlabeled implicit section
                (resolve-sections.ts) - every screen that hasn't been split
                into real sections yet (everything except purchase/header,
                for now) keeps looking exactly as it did before. A labeled
                section gets a real bordered surface with its own shadow
                (.schema-form-section, theme/global.css) - scoped to this
                class rather than every Card app-wide, since "Additional
                Cost"/"LME Records" etc. (PurchaseDetailScreen's own Cards)
                weren't part of this pass. */}
            <Card
              title={section.label || undefined}
              size="small"
              variant={section.label ? "outlined" : "borderless"}
              {...(section.label ? { className: "schema-form-section", styles: { body: { padding: "20px 24px" } } } : {})}
            >
              {section.description && (
                <Typography.Text type="secondary" className="section-description">
                  {section.description}
                </Typography.Text>
              )}
              <div className="field-grid">
                {section.fields.map((field) => (
                  <FieldRenderer key={field.fieldKey} field={field} control={control} mode={mode} uploadContext={uploadContext} />
                ))}
              </div>
            </Card>
          </ConfigProvider>
        ))}
        {(footer || submitError || mode !== "view") && (
          <div className="schema-form-actions">
            <Space direction="vertical" size="middle" style={{ width: "100%" }}>
              {footer}
              {submitError && <Alert type="error" showIcon message={submitError} />}
              {mode !== "view" && (
                <Space>
                  {onDiscard && (
                    <Popconfirm title="Discard unsaved changes?" onConfirm={onDiscard} okText="Discard" cancelText="Keep editing">
                      <Button>Discard</Button>
                    </Popconfirm>
                  )}
                  <Button type="primary" htmlType="submit">
                    Save
                  </Button>
                </Space>
              )}
            </Space>
          </div>
        )}
      </Space>
    </AntForm>
  );
}
