import type { ReactElement } from "react";
import { useController } from "react-hook-form";
import type { FieldComponentProps } from "./types";
import { FieldShell } from "./FieldShell";
import { ReadOnlyValue } from "./ReadOnlyValue";
import { asString } from "./field-value-utils";

/** Always read-only, regardless of mode - the server assigns this value on save (e.g. Purchase Number, Supplier Code). */
export function AutoGeneratedField({ field, control }: FieldComponentProps): ReactElement {
  const { field: rhf, fieldState } = useController({ name: field.fieldKey, control });
  const value = asString(rhf.value);

  return (
    <FieldShell fieldKey={field.fieldKey} label={field.label} mandatory={false} error={fieldState.error?.message}>
      <ReadOnlyValue id={field.fieldKey} value={value} emptyText="Generated on save" secondary />
    </FieldShell>
  );
}
