import type { ComponentType } from "react";
import type { FieldType } from "@ikration/contracts";
import type { FieldComponentProps } from "./types";
import { AutoGeneratedField } from "./AutoGeneratedField";
import { TextboxField } from "./TextboxField";
import { TextAreaField } from "./TextAreaField";
import { LookupField } from "./LookupField";
import { DatePickerField } from "./DatePickerField";
import { DecimalField } from "./DecimalField";
import { CurrencyField } from "./CurrencyField";
import { PercentageField } from "./PercentageField";
import { ToggleField } from "./ToggleField";
import { CalculatedField } from "./CalculatedField";
import { FileUploadField } from "./FileUploadField";
import { MultiUploadField } from "./MultiUploadField";

/**
 * The 13 field types from docs/spec/Purchase-V2.md §4, exactly. This is the
 * ONLY place that maps a field type to a component - never a switch on
 * field type anywhere else (frontend rule 6). "Dropdown" and "Lookup" are
 * two spec names for the SAME component: Lookup was always a strict
 * superset (search, cascading, allowCreate), so every select field gets
 * that behavior uniformly rather than maintaining two near-identical
 * implementations.
 */
export const fieldTypeRegistry: Record<FieldType, ComponentType<FieldComponentProps>> = {
  AutoGenerated: AutoGeneratedField,
  Textbox: TextboxField,
  TextArea: TextAreaField,
  Dropdown: LookupField,
  Lookup: LookupField,
  DatePicker: DatePickerField,
  Decimal: DecimalField,
  Currency: CurrencyField,
  Percentage: PercentageField,
  Toggle: ToggleField,
  Calculated: CalculatedField,
  FileUpload: FileUploadField,
  MultiUpload: MultiUploadField,
};
