import { ALL_MASTER_FIELD_DEFAULTS } from "../masters/registry.js";
import type { FieldSectionDefault } from "./group-sections.js";
import type { FieldDefault } from "./types.js";

/**
 * The single source of truth for every Tier 2 field this build knows
 * about - core/provisioning/seed-field-definitions.ts materializes one
 * field_definitions row per entry here for every company, and
 * core/field-engine/resolve.ts falls back to an entry here directly for
 * any tenant that hasn't been re-provisioned since an entry was added.
 * Adding a new configurable field to a module means adding it here, not
 * hand-writing a migration or a seed script.
 *
 * "purchase.po"'s Additional Cost fields are docs/spec/Purchase-V2.md
 * section G verbatim - Freight/Insurance/Customs are fixed-name Tier 2
 * (a real column, but nothing says the LABEL is configurable), and the
 * three "Other Charges" fields are explicitly called out in the spec as
 * "the reference case for the field engine": a real typed column with a
 * user-overridable label, nothing else. Renaming "Other Charges" to
 * "Clearing Charges" is exactly what this module exists to prove.
 */
export const FIELD_DEFAULTS: FieldDefault[] = [
  // FE-5.5's UserManagementScreen list columns - read-only (isEditable:
  // false everywhere): this entity's actual mutations go through the
  // dedicated suspend/reactivate/set-roles/invite/provision endpoints
  // below, never a generic PATCH on the field values themselves.
  {
    module: "users",
    entity: "user",
    fieldKey: "name",
    label: "Name",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: false,
    sortOrder: 0,
    isSystem: true,
  },
  {
    module: "users",
    entity: "user",
    fieldKey: "email",
    label: "Email",
    dataType: "text",
    isVisible: true,
    isMandatory: false,
    isEditable: false,
    sortOrder: 1,
    // A login identifier - see docs/adr/0006 on why email/mobile are both
    // nullable at the DB level, but whichever one a user has must stay
    // visible and reachable.
    isSystem: true,
  },
  {
    module: "users",
    entity: "user",
    fieldKey: "mobile",
    label: "Mobile",
    dataType: "text",
    isVisible: true,
    isMandatory: false,
    isEditable: false,
    sortOrder: 2,
    isSystem: true,
  },
  {
    module: "users",
    entity: "user",
    fieldKey: "status",
    label: "Status",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: false,
    sortOrder: 3,
    isSystem: true,
    // isEditable: false (list display only, per prompt 15) - SchemaTable
    // still needs a labeled value to render instead of the bare enum
    // string. Same active/inactive pair as company/branch (matching
    // admin-handlers.ts's convention, even though the mock's own user
    // field def omits optionsSource entirely) - "invited" is never a
    // value an admin picks from this dropdown, it's surfaced via the
    // separate invitationId/invitationExpiresAt fields instead.
    optionsSource: {
      type: "static",
      staticOptions: [
        { value: "active", label: "Active" },
        { value: "inactive", label: "Inactive" },
      ],
    },
  },
  {
    module: "users",
    entity: "user",
    fieldKey: "lastLoginAt",
    label: "Last Login",
    dataType: "datetime",
    isVisible: true,
    isMandatory: false,
    isEditable: false,
    sortOrder: 4,
    isSystem: true,
  },
  // Mirrors users.validator.ts's inviteUserSchema field-for-field (task
  // item 8) - no password field, admins never set passwords (BE-7,
  // docs/adr/0006-user-onboarding.md).
  {
    module: "users",
    entity: "invite",
    fieldKey: "name",
    label: "Name",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 0,
    isSystem: false,
  },
  {
    module: "users",
    entity: "invite",
    fieldKey: "email",
    label: "Email",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 1,
    isSystem: false,
    validationJson: { pattern: "^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$" },
  },
  {
    module: "users",
    entity: "invite",
    fieldKey: "mobile",
    label: "Mobile",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 2,
    isSystem: false,
  },
  {
    module: "users",
    entity: "invite",
    fieldKey: "roles",
    label: "Roles",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 3,
    isSystem: false,
    multiple: true,
    optionsSource: "roles",
  },
  // Mirrors provisionUserSchema field-for-field - the ops-staff exception
  // path (BE-7): a temp password, never an email.
  {
    module: "users",
    entity: "provision",
    fieldKey: "name",
    label: "Name",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 0,
    isSystem: false,
  },
  {
    module: "users",
    entity: "provision",
    fieldKey: "mobile",
    label: "Mobile",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 1,
    isSystem: false,
  },
  {
    module: "users",
    entity: "provision",
    fieldKey: "tempPassword",
    label: "Temporary Password",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 2,
    isSystem: false,
  },
  {
    module: "users",
    entity: "provision",
    fieldKey: "roles",
    label: "Roles",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 3,
    isSystem: false,
    multiple: true,
    optionsSource: "roles",
  },
  // PUT /api/v1/users/:id/roles's form - the full desired set (task item
  // 7), so `isMandatory: false` deliberately allows saving an empty array
  // (revoking every role from a user is a valid, if unusual, edit).
  {
    module: "users",
    entity: "edit-roles",
    fieldKey: "roleIds",
    label: "Roles",
    dataType: "select",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    sortOrder: 0,
    isSystem: false,
    multiple: true,
    optionsSource: "roles",
  },
  {
    module: "admin",
    entity: "company",
    fieldKey: "name",
    label: "Name",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 0,
    isSystem: true,
  },
  {
    module: "admin",
    entity: "company",
    fieldKey: "countryId",
    label: "Country",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 1,
    isSystem: false,
    optionsSource: "masters:countries",
  },
  {
    module: "admin",
    entity: "company",
    fieldKey: "currencyId",
    label: "Currency",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 2,
    isSystem: false,
    optionsSource: "masters:currencies",
  },
  {
    module: "admin",
    entity: "company",
    fieldKey: "fiscalYearStartMonth",
    label: "Fiscal Year Start Month",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 3,
    isSystem: false,
    optionsSource: {
      type: "static",
      staticOptions: [
        { value: "1", label: "January" },
        { value: "2", label: "February" },
        { value: "3", label: "March" },
        { value: "4", label: "April" },
        { value: "5", label: "May" },
        { value: "6", label: "June" },
        { value: "7", label: "July" },
        { value: "8", label: "August" },
        { value: "9", label: "September" },
        { value: "10", label: "October" },
        { value: "11", label: "November" },
        { value: "12", label: "December" },
      ],
    },
  },
  {
    module: "admin",
    entity: "company",
    fieldKey: "timezone",
    label: "Timezone",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 4,
    isSystem: false,
  },
  {
    module: "admin",
    entity: "company",
    fieldKey: "taxRegistrationNo",
    label: "Tax Registration No.",
    dataType: "text",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    sortOrder: 5,
    isSystem: false,
  },
  {
    module: "admin",
    entity: "company",
    fieldKey: "status",
    label: "Status",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 6,
    isSystem: false,
    optionsSource: {
      type: "static",
      staticOptions: [
        { value: "active", label: "Active" },
        { value: "inactive", label: "Inactive" },
      ],
    },
  },
  {
    module: "admin",
    entity: "branch",
    fieldKey: "name",
    label: "Name",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 0,
    isSystem: true,
  },
  {
    module: "admin",
    entity: "branch",
    fieldKey: "code",
    label: "Code",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 1,
    isSystem: true,
  },
  {
    module: "admin",
    entity: "branch",
    fieldKey: "status",
    label: "Status",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 2,
    isSystem: false,
    optionsSource: {
      type: "static",
      staticOptions: [
        { value: "active", label: "Active" },
        { value: "inactive", label: "Inactive" },
      ],
    },
    // company_id is deliberately NOT a field here - the backend injects it
    // from the request's tenant scope (backend rule 2), never a form field.
  },
  {
    module: "admin",
    entity: "role",
    fieldKey: "name",
    label: "Name",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 0,
    isSystem: true,
  },
  {
    module: "purchase",
    entity: "po",
    fieldKey: "freight",
    label: "Freight",
    dataType: "decimal",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    defaultValue: "0",
    sortOrder: 0,
    isSystem: false,
  },
  {
    module: "purchase",
    entity: "po",
    fieldKey: "insurance",
    label: "Insurance",
    dataType: "decimal",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    defaultValue: "0",
    sortOrder: 1,
    isSystem: false,
  },
  {
    module: "purchase",
    entity: "po",
    fieldKey: "customs",
    label: "Customs",
    dataType: "decimal",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    defaultValue: "0",
    sortOrder: 2,
    isSystem: false,
  },
  {
    module: "purchase",
    entity: "po",
    fieldKey: "otherCharges",
    label: "Other Charges",
    dataType: "decimal",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    defaultValue: "0",
    sortOrder: 3,
    isSystem: false,
  },
  {
    module: "purchase",
    entity: "po",
    fieldKey: "otherCharges2",
    label: "Other Charges 2",
    dataType: "decimal",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    defaultValue: "0",
    sortOrder: 4,
    isSystem: false,
  },
  {
    module: "purchase",
    entity: "po",
    fieldKey: "otherCharges3",
    label: "Other Charges 3",
    dataType: "decimal",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    defaultValue: "0",
    sortOrder: 5,
    isSystem: false,
  },
  // suppliers.validator.ts's createSupplierSchema field-for-field (prompt
  // 16 item 1) - "code" is FR-002's auto-generated value (read-only,
  // isSystem), everything else matches the create/update schemas exactly.
  {
    module: "suppliers",
    entity: "supplier",
    fieldKey: "code",
    label: "Supplier Code",
    dataType: "text",
    isVisible: true,
    isMandatory: false,
    isEditable: false,
    isSystem: true,
    sortOrder: 0,
    // FR-002's gapless, server-assigned code (number_series) - has no
    // value at all before creation, unlike a merely non-editable field.
    // apps/web's SchemaForm strips fieldType "AutoGenerated" keys from
    // its submit payload for exactly this reason (createSupplierSchema
    // is .strict() and never declares "code" as an allowed key).
    fieldType: "AutoGenerated",
  },
  {
    module: "suppliers",
    entity: "supplier",
    fieldKey: "name",
    label: "Supplier Name",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: true,
    sortOrder: 1,
  },
  {
    module: "suppliers",
    entity: "supplier",
    fieldKey: "supplierTypeId",
    label: "Supplier Type",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 2,
    optionsSource: "masters:supplier-types",
  },
  {
    module: "suppliers",
    entity: "supplier",
    fieldKey: "countryId",
    label: "Country",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 3,
    optionsSource: "masters:countries",
  },
  {
    // No dependsOn expressed (optionsSource is a plain string here, same
    // known gap as masters/registry.ts's own city module accepted for
    // itemType/status-style static options) - the real field-engine has no
    // wire convention yet for "this dropdown cascades off that other
    // field" (packages/contracts' own doc comment on optionsSourceSchema's
    // dependsOn: "no backend equivalent yet since no field needs it").
    // City still renders as a plain (uncascaded) country-wide list against
    // the real backend today.
    module: "suppliers",
    entity: "supplier",
    fieldKey: "cityId",
    label: "City",
    dataType: "select",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 4,
    optionsSource: "masters:cities",
  },
  {
    module: "suppliers",
    entity: "supplier",
    fieldKey: "address",
    label: "Address",
    dataType: "textarea",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 5,
  },
  {
    module: "suppliers",
    entity: "supplier",
    fieldKey: "taxRegistrationNo",
    label: "Tax Registration No.",
    dataType: "text",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 6,
  },
  {
    module: "suppliers",
    entity: "supplier",
    fieldKey: "paymentTermId",
    label: "Payment Terms",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 7,
    optionsSource: "masters:payment-terms",
  },
  {
    module: "suppliers",
    entity: "supplier",
    fieldKey: "currencyId",
    label: "Default Currency",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 8,
    optionsSource: "masters:currencies",
  },
  {
    module: "suppliers",
    entity: "supplier",
    fieldKey: "remarks",
    label: "Remarks",
    dataType: "textarea",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 9,
  },
  // brokers.validator.ts's createBrokerSchema/updateBrokerSchema field-for-
  // field (Prompt 21 item 4) - same shape/reasoning as the suppliers block
  // above, narrower (no supplierTypeId/countryId/cityId/paymentTermId/
  // currencyId - a broker isn't a trading counterparty with its own terms).
  {
    module: "brokers",
    entity: "broker",
    fieldKey: "code",
    label: "Broker Code",
    dataType: "text",
    isVisible: true,
    isMandatory: false,
    isEditable: false,
    isSystem: true,
    sortOrder: 0,
    fieldType: "AutoGenerated",
  },
  {
    module: "brokers",
    entity: "broker",
    fieldKey: "name",
    label: "Broker Name",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: true,
    sortOrder: 1,
  },
  {
    module: "brokers",
    entity: "broker",
    fieldKey: "remarks",
    label: "Remarks",
    dataType: "textarea",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 2,
  },
  // purchase.validator.ts's createPurchaseSchema/updatePurchaseSchema
  // flattened (prompt 16 item 2) - header fields + the nested `shipment`
  // sub-object's fields flattened to the top level (apps/web's
  // PurchaseDetailScreen.tsx splits them back into {header, shipment} on
  // submit - splitHeaderPayload), plus the 6 attachment fields, which
  // aren't part of either validator at all (they go through the separate
  // attachments REST endpoints, entity="purchase"/entityId=purchaseId/
  // fieldKey=<this fieldKey>).
  {
    module: "purchase",
    entity: "header",
    fieldKey: "purchaseNumber",
    section: "purchaseInfo",
    label: "Purchase Number",
    dataType: "text",
    isVisible: true,
    isMandatory: false,
    isEditable: false,
    isSystem: true,
    sortOrder: 0,
    // FR-101's gapless, server-assigned number (number_series) - has no
    // value at all before creation, unlike a merely non-editable field.
    // apps/web's SchemaForm strips fieldType "AutoGenerated" keys from
    // its submit payload for exactly this reason (createPurchaseSchema
    // never accepts "purchaseNumber").
    fieldType: "AutoGenerated",
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "divisionId",
    section: "purchaseInfo",
    label: "Division",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    // Prompt 21 item 1: selected first, before/above the rest of the
    // header - it scopes the purchase (a purchase cannot be created
    // without one). sortOrder 1, immediately after the read-only,
    // system-assigned Purchase Number - the first field a user actually
    // fills in.
    sortOrder: 1,
    optionsSource: "masters:divisions",
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "purchaseDate",
    section: "purchaseInfo",
    label: "Purchase Date",
    dataType: "date",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: true,
    sortOrder: 2,
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "branchId",
    section: "purchaseInfo",
    label: "Branch",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 3,
    optionsSource: "branches",
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "buyerId",
    section: "purchaseInfo",
    label: "Buyer",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 4,
    optionsSource: "companies",
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "supplierId",
    section: "purchaseInfo",
    label: "Supplier",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 5,
    optionsSource: "suppliers",
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "pricingType",
    section: "commercialDetails",
    label: "Pricing Type",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 6,
    // Prompt 21 item 2: drives which path is active - 'fixed' keeps the
    // manual item rate and hides LME Records; 'lme' shows LME Records and
    // the item rate is derived from its final rate
    // (purchase-items.service.ts). A fixed enum, not a master - the two
    // values are structural to the workflow, not tenant-configurable data.
    optionsSource: {
      type: "enum",
      staticOptions: [
        { label: "LME Purchase", value: "lme" },
        { label: "Fixed Price Purchase", value: "fixed" },
      ],
    },
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "supplierInvoiceNo",
    section: "commercialDetails",
    label: "Supplier Invoice No.",
    dataType: "text",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 7,
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "supplierReferenceNo",
    section: "commercialDetails",
    label: "Supplier Reference No.",
    dataType: "text",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 8,
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "brokerId",
    section: "commercialDetails",
    label: "Broker",
    dataType: "select",
    isVisible: true,
    // Prompt 21 item 4: nullable - "not every deal has a broker".
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 9,
    optionsSource: "brokers",
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "brokerCommission",
    section: "commercialDetails",
    label: "Broker Commission",
    dataType: "decimal",
    fieldType: "Currency",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 10,
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "lotNumber",
    section: "commercialDetails",
    label: "Shipment Lot Number",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 11,
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "containerId",
    section: "shipmentDetails",
    label: "Container Number",
    dataType: "select",
    fieldType: "Lookup",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 12,
    optionsSource: "masters:containers",
    // Prompt 21 item 5: was free text (containerNumber) - promoted to a
    // lookup against the containers master, but container numbers are too
    // numerous to expect pre-registration, so this Lookup allows
    // create-on-the-fly (core/schema-form/field-types/LookupField.tsx).
    allowCreate: true,
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "blNo",
    section: "shipmentDetails",
    label: "Bill of Lading No.",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 13,
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "loadingDate",
    section: "shipmentDetails",
    label: "Loading Date",
    dataType: "date",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 14,
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "transportModeId",
    section: "shipmentDetails",
    label: "Through",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 15,
    optionsSource: "masters:transport-modes",
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "vesselId",
    section: "shipmentDetails",
    label: "Vessel Name",
    dataType: "select",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 16,
    optionsSource: "masters:vessels",
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "voyageNumber",
    section: "shipmentDetails",
    label: "Voyage Number",
    dataType: "text",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 17,
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "portOfLoadingId",
    section: "shipmentDetails",
    label: "Port of Loading",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 18,
    optionsSource: "masters:ports",
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "portOfDischargeId",
    section: "shipmentDetails",
    label: "Port of Discharge",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 19,
    optionsSource: "masters:ports",
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "warehouseId",
    section: "shipmentDetails",
    label: "Warehouse",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 20,
    optionsSource: "masters:warehouses",
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "incotermId",
    section: "shipmentDetails",
    label: "Incoterm",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 21,
    optionsSource: "masters:incoterms",
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "invoice",
    section: "documents",
    label: "Invoice",
    dataType: "text",
    fieldType: "FileUpload",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 22,
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "billOfLading",
    section: "documents",
    label: "Bill of Lading",
    dataType: "text",
    fieldType: "FileUpload",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 23,
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "packingList",
    section: "documents",
    label: "Packing List",
    dataType: "text",
    fieldType: "FileUpload",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 24,
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "certificateOfOrigin",
    section: "documents",
    label: "Certificate of Origin",
    dataType: "text",
    fieldType: "FileUpload",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 25,
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "otherDocuments",
    section: "documents",
    label: "Other Documents",
    dataType: "text",
    fieldType: "MultiUpload",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 26,
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "otherDocuments2",
    section: "documents",
    label: "Other Documents 2",
    dataType: "text",
    fieldType: "MultiUpload",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 27,
  },
  // purchase-items.validator.ts's addPurchaseItemSchema field-for-field.
  {
    module: "purchase",
    entity: "item",
    fieldKey: "itemId",
    label: "Item",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 0,
    optionsSource: "masters:items",
  },
  {
    module: "purchase",
    entity: "item",
    fieldKey: "gradeId",
    label: "Grade",
    dataType: "select",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 1,
    optionsSource: "masters:item-grades",
  },
  {
    module: "purchase",
    entity: "item",
    fieldKey: "quantity",
    label: "Quantity",
    dataType: "decimal",
    fieldType: "Decimal",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 2,
  },
  {
    module: "purchase",
    entity: "item",
    fieldKey: "uomId",
    label: "Unit of Measure",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 3,
    optionsSource: "masters:uom",
  },
  {
    module: "purchase",
    entity: "item",
    fieldKey: "purchaseRateUsd",
    label: "Purchase Rate (USD)",
    dataType: "decimal",
    fieldType: "Currency",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: true,
    sortOrder: 4,
  },
  {
    module: "purchase",
    entity: "item",
    fieldKey: "exchangeRate",
    label: "Exchange Rate",
    dataType: "decimal",
    fieldType: "Decimal",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 5,
  },
  // purchase-allocations.validator.ts's addAllocationSchema field-for-field
  // - resolved one-to-many (prompt 16's decision): reservedCustomerId now
  // points at the real "customers" master (core/masters/registry.ts),
  // optionsSource "masters:customers", not the bare placeholder string
  // "customers" apps/web's mock used before that master existed.
  {
    module: "purchase",
    entity: "allocation",
    fieldKey: "reservedCustomerId",
    label: "Reserved Customer",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 0,
    optionsSource: "masters:customers",
  },
  {
    module: "purchase",
    entity: "allocation",
    fieldKey: "allocationPct",
    label: "Allocation %",
    dataType: "decimal",
    fieldType: "Percentage",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 1,
  },
  // purchase-lme.validator.ts's addLmeRecordSchema field-for-field.
  {
    module: "purchase",
    entity: "lme_record",
    fieldKey: "lmeExchangeId",
    label: "LME Exchange",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 0,
    optionsSource: "masters:lme-exchanges",
  },
  {
    module: "purchase",
    entity: "lme_record",
    fieldKey: "metal",
    label: "Metal",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 1,
  },
  {
    module: "purchase",
    entity: "lme_record",
    fieldKey: "lmeType",
    label: "LME Type",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 2,
    // Prompt 21 item 3: a categorization field only - no calculation
    // depends on it yet.
    optionsSource: {
      type: "enum",
      staticOptions: [
        { label: "Open", value: "open" },
        { label: "Close", value: "close" },
        { label: "Cash", value: "cash" },
      ],
    },
  },
  {
    module: "purchase",
    entity: "lme_record",
    fieldKey: "lmePriceUsd",
    label: "LME Purchase Price (USD)",
    dataType: "decimal",
    fieldType: "Currency",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 3,
  },
  {
    module: "purchase",
    entity: "lme_record",
    fieldKey: "fixingDate",
    label: "LME Fixing Date",
    dataType: "date",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 4,
  },
  {
    module: "purchase",
    entity: "lme_record",
    fieldKey: "agreedPremiumPct",
    // Renamed from "Agreed Premium (%)" (client-confirmed correction): the
    // value is a direct percentage multiplier of the LME price (98% means
    // final = 98% of LME), never an additive markup - "Premium" implied
    // the wrong thing even though the underlying column/field key still
    // says "premium" (not worth a migration to rename).
    label: "Agreed %",
    dataType: "decimal",
    fieldType: "Percentage",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 5,
  },
  // purchase-hedges.validator.ts's addHedgeSchema field-for-field.
  {
    module: "purchase",
    entity: "hedge",
    fieldKey: "hedgePlatformId",
    label: "Hedge Platform",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 0,
    optionsSource: "masters:hedge-platforms",
  },
  {
    module: "purchase",
    entity: "hedge",
    fieldKey: "contractNumber",
    label: "Hedge Contract Number",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 1,
  },
  {
    // "buy"/"sell" is a fixed enum, not a master-backed dropdown - matches
    // purchase-handlers.ts's HEDGE_FIELDS mock exactly (its own inline
    // optionsSource for this field, the only mock precedent for the
    // object form rather than a master/roles bare string).
    module: "purchase",
    entity: "hedge",
    fieldKey: "position",
    label: "Hedge Position",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 2,
    optionsSource: {
      type: "enum",
      staticOptions: [
        { value: "buy", label: "Buy" },
        { value: "sell", label: "Sell" },
      ],
    },
  },
  {
    module: "purchase",
    entity: "hedge",
    fieldKey: "quantity",
    label: "Hedge Quantity",
    dataType: "decimal",
    fieldType: "Decimal",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 3,
  },
  {
    module: "purchase",
    entity: "hedge",
    fieldKey: "rate",
    label: "Hedge Rate",
    dataType: "decimal",
    fieldType: "Currency",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 4,
  },
  {
    module: "purchase",
    entity: "hedge",
    fieldKey: "hedgeDate",
    label: "Hedge Date",
    dataType: "date",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 5,
  },
  // Prompt 22 item 2: the supplier invoice - the NEW document that moves
  // stock (Part 3), not the purchase's own approval. invoiceNumber is
  // this system's own gapless number (AutoGenerated, same treatment as
  // purchaseNumber); supplierInvoiceNo is the supplier's own free-text
  // reference (distinct field, same as it already was on purchase/header
  // before this prompt). invoiceFile is the uploaded document itself
  // (core/storage's existing entity-agnostic attachments service, entity
  // "purchase_invoice").
  {
    module: "purchase",
    entity: "invoice",
    fieldKey: "invoiceNumber",
    label: "Invoice Number",
    dataType: "text",
    fieldType: "AutoGenerated",
    isVisible: true,
    isMandatory: false,
    isEditable: false,
    isSystem: true,
    sortOrder: 0,
  },
  {
    module: "purchase",
    entity: "invoice",
    fieldKey: "supplierInvoiceNo",
    label: "Supplier Invoice No.",
    dataType: "text",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 1,
  },
  {
    module: "purchase",
    entity: "invoice",
    fieldKey: "invoiceDate",
    label: "Invoice Date",
    dataType: "date",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 2,
  },
  {
    module: "purchase",
    entity: "invoice",
    fieldKey: "invoiceAmountUsd",
    label: "Invoice Amount (USD)",
    dataType: "decimal",
    fieldType: "Currency",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 3,
  },
  {
    module: "purchase",
    entity: "invoice",
    fieldKey: "invoiceFile",
    label: "Invoice Document",
    dataType: "text",
    fieldType: "FileUpload",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 4,
  },
  // FE-7's field-permission demo needs a real, resolvable field to prove
  // "revoke can_view -> the very next GET /field-definitions/purchase/
  // pricing for that role no longer shows it" (this task's own acceptance
  // test) - purchase_pricing.purchaseRateUsd (schema.ts) is that field.
  // Declaring it here doesn't make it Tier-2/company-overridable in the
  // CLAUDE.md sense (it's still a fixed, typed rate column the purchase
  // module writes directly) - it only enrolls it in the field-engine's
  // resolve pipeline, which is what field_permissions' view/edit narrowing
  // (core/rbac/resolve.ts) needs to have anything to narrow.
  {
    module: "purchase",
    entity: "pricing",
    fieldKey: "purchaseRateUsd",
    label: "Purchase Rate (USD)",
    dataType: "decimal",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 0,
    isSystem: true,
  },
  // Every masters.<entity> Tier-2 field (code/name/isActive + each
  // master's own extras, e.g. cities.countryId) - generated from
  // core/masters/registry.ts's MASTER_MODULES rather than hand-duplicated
  // here, so a 16th master needs zero changes to this file.
  ...ALL_MASTER_FIELD_DEFAULTS,
];

export function getFieldDefaults(module: string, entity: string): FieldDefault[] {
  return FIELD_DEFAULTS.filter((field) => field.module === module && field.entity === entity);
}

/**
 * Which (module, entity) pairs are split into sections, and what each
 * section is called - code-declared, same as FIELD_DEFAULTS itself. Only
 * purchase/header is split today (Prompt 23's redesign); every other
 * entity has no entry here and keeps returning a flat `fields` list
 * exactly as before (core/field-engine/group-sections.ts's
 * groupFieldsIntoSections returns undefined for an empty list).
 */
export const SECTION_DEFAULTS: FieldSectionDefault[] = [
  {
    module: "purchase",
    entity: "header",
    key: "purchaseInfo",
    label: "Purchase Information",
    description: "Basic information about this purchase",
    sortOrder: 0,
  },
  {
    module: "purchase",
    entity: "header",
    key: "commercialDetails",
    label: "Commercial Details",
    description: "Pricing, invoice, broker and reference information",
    sortOrder: 1,
  },
  {
    module: "purchase",
    entity: "header",
    key: "shipmentDetails",
    label: "Shipment Details",
    description: "Container, vessel, ports, warehouse and shipping information",
    sortOrder: 2,
  },
  {
    module: "purchase",
    entity: "header",
    key: "documents",
    label: "Documents",
    description: "Supporting documents for this purchase",
    sortOrder: 3,
  },
];

export function getFieldSections(module: string, entity: string): FieldSectionDefault[] {
  return SECTION_DEFAULTS.filter((section) => section.module === module && section.entity === entity);
}
