import { ALL_MASTER_FIELD_DEFAULTS } from "../masters/registry.js";
import type { FieldDefault } from "./types.js";

/**
 * The single source of truth for every Tier 2 field this build knows
 * about - core/provisioning/seed-field-definitions.ts materializes one
 * field_definitions row per entry here for every company, and
 * core/field-engine/resolve.ts falls back to an entry here directly for
 * any tenant that hasn't been re-provisioned since an entry was added.
 * Adding a new configurable field to a module means adding it here, not
 * hand-writing a migration or a seed script.
 *
 * "purchase.po"'s Additional Cost fields are docs/spec/Purchase-V2.md
 * section G verbatim - Freight/Insurance/Customs are fixed-name Tier 2
 * (a real column, but nothing says the LABEL is configurable), and the
 * three "Other Charges" fields are explicitly called out in the spec as
 * "the reference case for the field engine": a real typed column with a
 * user-overridable label, nothing else. Renaming "Other Charges" to
 * "Clearing Charges" is exactly what this module exists to prove.
 */
export const FIELD_DEFAULTS: FieldDefault[] = [
  // FE-5.5's UserManagementScreen list columns - read-only (isEditable:
  // false everywhere): this entity's actual mutations go through the
  // dedicated suspend/reactivate/set-roles/invite/provision endpoints
  // below, never a generic PATCH on the field values themselves.
  {
    module: "users",
    entity: "user",
    fieldKey: "name",
    label: "Name",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: false,
    sortOrder: 0,
    isSystem: true,
  },
  {
    module: "users",
    entity: "user",
    fieldKey: "email",
    label: "Email",
    dataType: "text",
    isVisible: true,
    isMandatory: false,
    isEditable: false,
    sortOrder: 1,
    // A login identifier - see docs/adr/0006 on why email/mobile are both
    // nullable at the DB level, but whichever one a user has must stay
    // visible and reachable.
    isSystem: true,
  },
  {
    module: "users",
    entity: "user",
    fieldKey: "mobile",
    label: "Mobile",
    dataType: "text",
    isVisible: true,
    isMandatory: false,
    isEditable: false,
    sortOrder: 2,
    isSystem: true,
  },
  {
    module: "users",
    entity: "user",
    fieldKey: "status",
    label: "Status",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: false,
    sortOrder: 3,
    isSystem: true,
  },
  {
    module: "users",
    entity: "user",
    fieldKey: "lastLoginAt",
    label: "Last Login",
    dataType: "datetime",
    isVisible: true,
    isMandatory: false,
    isEditable: false,
    sortOrder: 4,
    isSystem: true,
  },
  // Mirrors users.validator.ts's inviteUserSchema field-for-field (task
  // item 8) - no password field, admins never set passwords (BE-7,
  // docs/adr/0006-user-onboarding.md).
  {
    module: "users",
    entity: "invite",
    fieldKey: "name",
    label: "Name",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 0,
    isSystem: false,
  },
  {
    module: "users",
    entity: "invite",
    fieldKey: "email",
    label: "Email",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 1,
    isSystem: false,
    validationJson: { pattern: "^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$" },
  },
  {
    module: "users",
    entity: "invite",
    fieldKey: "mobile",
    label: "Mobile",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 2,
    isSystem: false,
  },
  {
    module: "users",
    entity: "invite",
    fieldKey: "roles",
    label: "Roles",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 3,
    isSystem: false,
    multiple: true,
    optionsSource: "roles",
  },
  // Mirrors provisionUserSchema field-for-field - the ops-staff exception
  // path (BE-7): a temp password, never an email.
  {
    module: "users",
    entity: "provision",
    fieldKey: "name",
    label: "Name",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 0,
    isSystem: false,
  },
  {
    module: "users",
    entity: "provision",
    fieldKey: "mobile",
    label: "Mobile",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 1,
    isSystem: false,
  },
  {
    module: "users",
    entity: "provision",
    fieldKey: "tempPassword",
    label: "Temporary Password",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 2,
    isSystem: false,
  },
  {
    module: "users",
    entity: "provision",
    fieldKey: "roles",
    label: "Roles",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 3,
    isSystem: false,
    multiple: true,
    optionsSource: "roles",
  },
  // PUT /api/v1/users/:id/roles's form - the full desired set (task item
  // 7), so `isMandatory: false` deliberately allows saving an empty array
  // (revoking every role from a user is a valid, if unusual, edit).
  {
    module: "users",
    entity: "edit-roles",
    fieldKey: "roleIds",
    label: "Roles",
    dataType: "select",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    sortOrder: 0,
    isSystem: false,
    multiple: true,
    optionsSource: "roles",
  },
  {
    module: "admin",
    entity: "company",
    fieldKey: "name",
    label: "Name",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 0,
    isSystem: true,
  },
  {
    module: "admin",
    entity: "company",
    fieldKey: "countryId",
    label: "Country",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 1,
    isSystem: false,
    optionsSource: "masters:countries",
  },
  {
    module: "admin",
    entity: "company",
    fieldKey: "currencyId",
    label: "Currency",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 2,
    isSystem: false,
    optionsSource: "masters:currencies",
  },
  {
    // No optionsSource: a fixed 1-12 static list, same gap as masters'
    // itemType below - the real field-engine's FieldDefault.optionsSource
    // convention only covers "masters:<x>"/"roles" today, not an inline
    // static option list (packages/contracts' richer `{type:"static",...}"
    // shape is an apps/web dev-fixture-only convention, not something this
    // backend emits yet).
    module: "admin",
    entity: "company",
    fieldKey: "fiscalYearStartMonth",
    label: "Fiscal Year Start Month",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 3,
    isSystem: false,
  },
  {
    module: "admin",
    entity: "company",
    fieldKey: "timezone",
    label: "Timezone",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 4,
    isSystem: false,
  },
  {
    module: "admin",
    entity: "company",
    fieldKey: "taxRegistrationNo",
    label: "Tax Registration No.",
    dataType: "text",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    sortOrder: 5,
    isSystem: false,
  },
  {
    module: "admin",
    entity: "company",
    fieldKey: "status",
    label: "Status",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 6,
    isSystem: false,
  },
  {
    module: "admin",
    entity: "branch",
    fieldKey: "name",
    label: "Name",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 0,
    isSystem: true,
  },
  {
    module: "admin",
    entity: "branch",
    fieldKey: "code",
    label: "Code",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 1,
    isSystem: true,
  },
  {
    module: "admin",
    entity: "branch",
    fieldKey: "status",
    label: "Status",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 2,
    isSystem: false,
    // company_id is deliberately NOT a field here - the backend injects it
    // from the request's tenant scope (backend rule 2), never a form field.
  },
  {
    module: "admin",
    entity: "role",
    fieldKey: "name",
    label: "Name",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 0,
    isSystem: true,
  },
  {
    module: "purchase",
    entity: "po",
    fieldKey: "freight",
    label: "Freight",
    dataType: "decimal",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    defaultValue: "0",
    sortOrder: 0,
    isSystem: false,
  },
  {
    module: "purchase",
    entity: "po",
    fieldKey: "insurance",
    label: "Insurance",
    dataType: "decimal",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    defaultValue: "0",
    sortOrder: 1,
    isSystem: false,
  },
  {
    module: "purchase",
    entity: "po",
    fieldKey: "customs",
    label: "Customs",
    dataType: "decimal",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    defaultValue: "0",
    sortOrder: 2,
    isSystem: false,
  },
  {
    module: "purchase",
    entity: "po",
    fieldKey: "otherCharges",
    label: "Other Charges",
    dataType: "decimal",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    defaultValue: "0",
    sortOrder: 3,
    isSystem: false,
  },
  {
    module: "purchase",
    entity: "po",
    fieldKey: "otherCharges2",
    label: "Other Charges 2",
    dataType: "decimal",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    defaultValue: "0",
    sortOrder: 4,
    isSystem: false,
  },
  {
    module: "purchase",
    entity: "po",
    fieldKey: "otherCharges3",
    label: "Other Charges 3",
    dataType: "decimal",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    defaultValue: "0",
    sortOrder: 5,
    isSystem: false,
  },
  // suppliers.validator.ts's createSupplierSchema field-for-field (prompt
  // 16 item 1) - "code" is FR-002's auto-generated value (read-only,
  // isSystem), everything else matches the create/update schemas exactly.
  {
    module: "suppliers",
    entity: "supplier",
    fieldKey: "code",
    label: "Supplier Code",
    dataType: "text",
    isVisible: true,
    isMandatory: false,
    isEditable: false,
    isSystem: true,
    sortOrder: 0,
  },
  {
    module: "suppliers",
    entity: "supplier",
    fieldKey: "name",
    label: "Supplier Name",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: true,
    sortOrder: 1,
  },
  {
    module: "suppliers",
    entity: "supplier",
    fieldKey: "supplierTypeId",
    label: "Supplier Type",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 2,
    optionsSource: "masters:supplier-types",
  },
  {
    module: "suppliers",
    entity: "supplier",
    fieldKey: "countryId",
    label: "Country",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 3,
    optionsSource: "masters:countries",
  },
  {
    // No dependsOn expressed (optionsSource is a plain string here, same
    // known gap as masters/registry.ts's own city module accepted for
    // itemType/status-style static options) - the real field-engine has no
    // wire convention yet for "this dropdown cascades off that other
    // field" (packages/contracts' own doc comment on optionsSourceSchema's
    // dependsOn: "no backend equivalent yet since no field needs it").
    // City still renders as a plain (uncascaded) country-wide list against
    // the real backend today.
    module: "suppliers",
    entity: "supplier",
    fieldKey: "cityId",
    label: "City",
    dataType: "select",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 4,
    optionsSource: "masters:cities",
  },
  {
    module: "suppliers",
    entity: "supplier",
    fieldKey: "address",
    label: "Address",
    dataType: "textarea",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 5,
  },
  {
    module: "suppliers",
    entity: "supplier",
    fieldKey: "taxRegistrationNo",
    label: "Tax Registration No.",
    dataType: "text",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 6,
  },
  {
    module: "suppliers",
    entity: "supplier",
    fieldKey: "paymentTermId",
    label: "Payment Terms",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 7,
    optionsSource: "masters:payment-terms",
  },
  {
    module: "suppliers",
    entity: "supplier",
    fieldKey: "currencyId",
    label: "Default Currency",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 8,
    optionsSource: "masters:currencies",
  },
  {
    module: "suppliers",
    entity: "supplier",
    fieldKey: "remarks",
    label: "Remarks",
    dataType: "textarea",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 9,
  },
  // purchase.validator.ts's createPurchaseSchema/updatePurchaseSchema
  // flattened (prompt 16 item 2) - header fields + the nested `shipment`
  // sub-object's fields flattened to the top level (apps/web's
  // PurchaseDetailScreen.tsx splits them back into {header, shipment} on
  // submit - splitHeaderPayload), plus the 6 attachment fields, which
  // aren't part of either validator at all (they go through the separate
  // attachments REST endpoints, entity="purchase"/entityId=purchaseId/
  // fieldKey=<this fieldKey>).
  {
    module: "purchase",
    entity: "header",
    fieldKey: "purchaseNumber",
    label: "Purchase Number",
    dataType: "text",
    isVisible: true,
    isMandatory: false,
    isEditable: false,
    isSystem: true,
    sortOrder: 0,
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "purchaseDate",
    label: "Purchase Date",
    dataType: "date",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: true,
    sortOrder: 1,
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "branchId",
    label: "Branch",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 2,
    optionsSource: "branches",
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "buyerId",
    label: "Buyer",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 3,
    optionsSource: "users",
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "supplierId",
    label: "Supplier",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 4,
    optionsSource: "suppliers",
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "supplierInvoiceNo",
    label: "Supplier Invoice No.",
    dataType: "text",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 5,
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "supplierReferenceNo",
    label: "Supplier Reference No.",
    dataType: "text",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 6,
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "lotNumber",
    label: "Shipment Lot Number",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 7,
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "containerNumber",
    label: "Container Number",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 8,
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "blNo",
    label: "Bill of Lading No.",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 9,
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "loadingDate",
    label: "Loading Date",
    dataType: "date",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 10,
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "transportModeId",
    label: "Through",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 11,
    optionsSource: "masters:transport-modes",
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "vesselId",
    label: "Vessel Name",
    dataType: "select",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 12,
    optionsSource: "masters:vessels",
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "voyageNumber",
    label: "Voyage Number",
    dataType: "text",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 13,
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "portOfLoadingId",
    label: "Port of Loading",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 14,
    optionsSource: "masters:ports",
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "portOfDischargeId",
    label: "Port of Discharge",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 15,
    optionsSource: "masters:ports",
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "warehouseId",
    label: "Warehouse",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 16,
    optionsSource: "masters:warehouses",
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "incotermId",
    label: "Incoterm",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 17,
    optionsSource: "masters:incoterms",
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "invoice",
    label: "Invoice",
    dataType: "text",
    fieldType: "FileUpload",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 18,
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "billOfLading",
    label: "Bill of Lading",
    dataType: "text",
    fieldType: "FileUpload",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 19,
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "packingList",
    label: "Packing List",
    dataType: "text",
    fieldType: "FileUpload",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 20,
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "certificateOfOrigin",
    label: "Certificate of Origin",
    dataType: "text",
    fieldType: "FileUpload",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 21,
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "otherDocuments",
    label: "Other Documents",
    dataType: "text",
    fieldType: "MultiUpload",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 22,
  },
  {
    module: "purchase",
    entity: "header",
    fieldKey: "otherDocuments2",
    label: "Other Documents 2",
    dataType: "text",
    fieldType: "MultiUpload",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 23,
  },
  // purchase-items.validator.ts's addPurchaseItemSchema field-for-field.
  {
    module: "purchase",
    entity: "item",
    fieldKey: "itemId",
    label: "Item",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 0,
    optionsSource: "masters:items",
  },
  {
    module: "purchase",
    entity: "item",
    fieldKey: "gradeId",
    label: "Grade",
    dataType: "select",
    isVisible: true,
    isMandatory: false,
    isEditable: true,
    isSystem: false,
    sortOrder: 1,
    optionsSource: "masters:item-grades",
  },
  {
    module: "purchase",
    entity: "item",
    fieldKey: "quantity",
    label: "Quantity",
    dataType: "decimal",
    fieldType: "Decimal",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 2,
  },
  {
    module: "purchase",
    entity: "item",
    fieldKey: "uomId",
    label: "Unit of Measure",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 3,
    optionsSource: "masters:uom",
  },
  {
    module: "purchase",
    entity: "item",
    fieldKey: "purchaseRateUsd",
    label: "Purchase Rate (USD)",
    dataType: "decimal",
    fieldType: "Currency",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: true,
    sortOrder: 4,
  },
  {
    module: "purchase",
    entity: "item",
    fieldKey: "exchangeRate",
    label: "Exchange Rate",
    dataType: "decimal",
    fieldType: "Decimal",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 5,
  },
  // purchase-allocations.validator.ts's addAllocationSchema field-for-field
  // - resolved one-to-many (prompt 16's decision): reservedCustomerId now
  // points at the real "customers" master (core/masters/registry.ts),
  // optionsSource "masters:customers", not the bare placeholder string
  // "customers" apps/web's mock used before that master existed.
  {
    module: "purchase",
    entity: "allocation",
    fieldKey: "reservedCustomerId",
    label: "Reserved Customer",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 0,
    optionsSource: "masters:customers",
  },
  {
    module: "purchase",
    entity: "allocation",
    fieldKey: "allocationPct",
    label: "Allocation %",
    dataType: "decimal",
    fieldType: "Percentage",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 1,
  },
  // purchase-lme.validator.ts's addLmeRecordSchema field-for-field.
  {
    module: "purchase",
    entity: "lme_record",
    fieldKey: "lmeExchangeId",
    label: "LME Exchange",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 0,
    optionsSource: "masters:lme-exchanges",
  },
  {
    module: "purchase",
    entity: "lme_record",
    fieldKey: "metal",
    label: "Metal",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 1,
  },
  {
    module: "purchase",
    entity: "lme_record",
    fieldKey: "lmePriceUsd",
    label: "LME Purchase Price (USD)",
    dataType: "decimal",
    fieldType: "Currency",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 2,
  },
  {
    module: "purchase",
    entity: "lme_record",
    fieldKey: "fixingDate",
    label: "LME Fixing Date",
    dataType: "date",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 3,
  },
  {
    module: "purchase",
    entity: "lme_record",
    fieldKey: "agreedPremiumPct",
    label: "Agreed Premium (%)",
    dataType: "decimal",
    fieldType: "Percentage",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 4,
  },
  // purchase-hedges.validator.ts's addHedgeSchema field-for-field.
  {
    module: "purchase",
    entity: "hedge",
    fieldKey: "hedgePlatformId",
    label: "Hedge Platform",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 0,
    optionsSource: "masters:hedge-platforms",
  },
  {
    module: "purchase",
    entity: "hedge",
    fieldKey: "contractNumber",
    label: "Hedge Contract Number",
    dataType: "text",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 1,
  },
  {
    // No optionsSource (same static-2-value-enum gap already accepted for
    // admin/company's status field) - "buy"/"sell" is a fixed enum, not a
    // master-backed dropdown.
    module: "purchase",
    entity: "hedge",
    fieldKey: "position",
    label: "Hedge Position",
    dataType: "select",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 2,
  },
  {
    module: "purchase",
    entity: "hedge",
    fieldKey: "quantity",
    label: "Hedge Quantity",
    dataType: "decimal",
    fieldType: "Decimal",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 3,
  },
  {
    module: "purchase",
    entity: "hedge",
    fieldKey: "rate",
    label: "Hedge Rate",
    dataType: "decimal",
    fieldType: "Currency",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 4,
  },
  {
    module: "purchase",
    entity: "hedge",
    fieldKey: "hedgeDate",
    label: "Hedge Date",
    dataType: "date",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    isSystem: false,
    sortOrder: 5,
  },
  // FE-7's field-permission demo needs a real, resolvable field to prove
  // "revoke can_view -> the very next GET /field-definitions/purchase/
  // pricing for that role no longer shows it" (this task's own acceptance
  // test) - purchase_pricing.purchaseRateUsd (schema.ts) is that field.
  // Declaring it here doesn't make it Tier-2/company-overridable in the
  // CLAUDE.md sense (it's still a fixed, typed rate column the purchase
  // module writes directly) - it only enrolls it in the field-engine's
  // resolve pipeline, which is what field_permissions' view/edit narrowing
  // (core/rbac/resolve.ts) needs to have anything to narrow.
  {
    module: "purchase",
    entity: "pricing",
    fieldKey: "purchaseRateUsd",
    label: "Purchase Rate (USD)",
    dataType: "decimal",
    isVisible: true,
    isMandatory: true,
    isEditable: true,
    sortOrder: 0,
    isSystem: true,
  },
  // Every masters.<entity> Tier-2 field (code/name/isActive + each
  // master's own extras, e.g. cities.countryId) - generated from
  // core/masters/registry.ts's MASTER_MODULES rather than hand-duplicated
  // here, so a 16th master needs zero changes to this file.
  ...ALL_MASTER_FIELD_DEFAULTS,
];

export function getFieldDefaults(module: string, entity: string): FieldDefault[] {
  return FIELD_DEFAULTS.filter((field) => field.module === module && field.entity === entity);
}
