import type { FieldValidationRules } from "../../database/tenant/schema.js";

export type { FieldValidationRules } from "../../database/tenant/schema.js";

export type FieldDataType =
  | "text"
  | "textarea"
  | "number"
  | "decimal"
  | "boolean"
  | "date"
  | "datetime"
  | "select";

/**
 * Mirrors packages/contracts/src/field-definitions.ts's fieldTypeSchema
 * (the 13-value widget-level enum) - normally the frontend derives a
 * fieldType from dataType alone when this is absent (apps/web's
 * resolve-field-type.ts), which is fine for most fields (Currency/
 * Percentage both just render as "Decimal", a cosmetic simplification).
 * It stops being cosmetic for FileUpload/MultiUpload: those have no
 * dataType equivalent at all (the closest is "text", which would resolve
 * to a plain Textbox) - a file field is functionally broken, not just
 * unstyled, without an explicit fieldType. Set only where dataType alone
 * is genuinely ambiguous or wrong, not as a matter of course.
 */
export type FieldType =
  | "AutoGenerated"
  | "Textbox"
  | "TextArea"
  | "Dropdown"
  | "Lookup"
  | "DatePicker"
  | "Decimal"
  | "Currency"
  | "Percentage"
  | "Toggle"
  | "Calculated"
  | "FileUpload"
  | "MultiUpload";

/**
 * The code-declared baseline for a Tier 2 field (core/field-engine/
 * defaults.ts) - what a field looks like before any company has
 * overridden anything. `fieldKey`/`dataType`/`tier` are exactly the
 * properties a company override can never touch (CLAUDE.md: "data_type is
 * NEVER overridable"; field_key is the real column identifier, immutable
 * by construction since it's never part of the PATCH schema at all).
 */
export interface FieldDefault {
  module: string;
  entity: string;
  fieldKey: string;
  label: string;
  dataType: FieldDataType;
  isVisible: boolean;
  isMandatory: boolean;
  isEditable: boolean;
  defaultValue?: string;
  optionsSource?: string;
  fieldType?: FieldType;
  /** Dropdown only - a role picker etc. renders as a multi-select and stores an array, not a single string. Mirrors packages/contracts/src/field-definitions.ts's fieldDefinitionSchema.multiple. */
  multiple?: boolean;
  validationJson?: FieldValidationRules;
  sortOrder: number;
  isSystem: boolean;
}

/**
 * What core/field-engine/resolve.ts actually returns: a FieldDefault's
 * shape, further narrowed by the requesting user's RBAC field
 * permissions (core/rbac) - `isVisible`/`isEditable` here are the FINAL,
 * already-intersected values a form can trust directly, not just the
 * company-level override.
 */
export interface EffectiveField {
  id: string | undefined;
  module: string;
  entity: string;
  fieldKey: string;
  tier: 2;
  label: string;
  dataType: FieldDataType;
  isVisible: boolean;
  isMandatory: boolean;
  isEditable: boolean;
  defaultValue: string | undefined;
  optionsSource: string | undefined;
  fieldType: FieldType | undefined;
  multiple: boolean | undefined;
  validationJson: FieldValidationRules | undefined;
  sortOrder: number;
  isSystem: boolean;
}
