import type { FieldValidationRules } from "../../database/tenant/schema.js";

export type { FieldValidationRules } from "../../database/tenant/schema.js";

export type FieldDataType =
  | "text"
  | "textarea"
  | "number"
  | "decimal"
  | "boolean"
  | "date"
  | "datetime"
  | "select";

/**
 * Mirrors packages/contracts/src/field-definitions.ts's fieldTypeSchema
 * (the 13-value widget-level enum) - normally the frontend derives a
 * fieldType from dataType alone when this is absent (apps/web's
 * resolve-field-type.ts), which is fine for most fields (Currency/
 * Percentage both just render as "Decimal", a cosmetic simplification).
 * It stops being cosmetic for FileUpload/MultiUpload: those have no
 * dataType equivalent at all (the closest is "text", which would resolve
 * to a plain Textbox) - a file field is functionally broken, not just
 * unstyled, without an explicit fieldType. Set only where dataType alone
 * is genuinely ambiguous or wrong, not as a matter of course.
 */
export type FieldType =
  | "AutoGenerated"
  | "Textbox"
  | "TextArea"
  | "Dropdown"
  | "Lookup"
  | "DatePicker"
  | "Decimal"
  | "Currency"
  | "Percentage"
  | "Toggle"
  | "Calculated"
  | "FileUpload"
  | "MultiUpload";

export interface StaticOption {
  value: string;
  label: string;
}

/**
 * A `dataType: "select"` field whose choices are a fixed, code-owned enum
 * (active/inactive, months 1-12, buy/sell) - never a masters/roles
 * reference (those stay a bare string, e.g. "masters:countries").
 * Mirrors packages/contracts/src/field-definitions.ts's
 * optionsSourceObjectSchema exactly - `type: "static"` and `type: "enum"`
 * are parsed identically there (apps/web never branches on which), so
 * either is fine here too. Every select field needs SOME optionsSource -
 * a bare enum with nothing else to point at is exactly the bug this type
 * exists to make impossible again (see FIELD_DEFAULTS's own guard test).
 */
export interface StaticOptionsSource {
  type: "static" | "enum";
  staticOptions: StaticOption[];
}

/**
 * The DB's field_definitions.options_source column is a plain TEXT
 * column (opaque bare-string convention, e.g. "masters:countries") - it
 * can never store the richer object form, so a row only ever contributes
 * a string to the merged result (core/field-engine/resolve.ts's
 * mergeRow), never a StaticOptionsSource. The object form only ever comes
 * from the code default itself.
 */
export type FieldOptionsSource = string | StaticOptionsSource;

/**
 * The code-declared baseline for a Tier 2 field (core/field-engine/
 * defaults.ts) - what a field looks like before any company has
 * overridden anything. `fieldKey`/`dataType`/`tier` are exactly the
 * properties a company override can never touch (CLAUDE.md: "data_type is
 * NEVER overridable"; field_key is the real column identifier, immutable
 * by construction since it's never part of the PATCH schema at all).
 */
export interface FieldDefault {
  module: string;
  entity: string;
  fieldKey: string;
  label: string;
  dataType: FieldDataType;
  isVisible: boolean;
  isMandatory: boolean;
  isEditable: boolean;
  defaultValue?: string;
  optionsSource?: FieldOptionsSource;
  fieldType?: FieldType;
  /** Dropdown only - a role picker etc. renders as a multi-select and stores an array, not a single string. Mirrors packages/contracts/src/field-definitions.ts's fieldDefinitionSchema.multiple. */
  multiple?: boolean;
  /** Lookup only (Prompt 21 item 5) - lets the field's own Select create a new row in the referenced master inline when nothing matches, rather than requiring pre-registration. Per-company field_definitions row override (PATCH-able via admin.field.manage, same as label/isVisible/isMandatory), NOT structural like dataType - this value is just the starting default a new tenant is seeded with. The create POST target/payload varies by source: most fields hit the generic `/masters/:urlSegment` with `{code, name}` = the search text, but some sources (e.g. companies) are routed by apps/web/src/core/schema-form/field-types/LookupField.tsx's NON_MASTER_CREATE_ENDPOINTS to their own endpoint/payload instead. */
  allowCreate?: boolean;
  validationJson?: FieldValidationRules;
  sortOrder: number;
  isSystem: boolean;
  /** Groups this field under a FieldSectionDefault's key (core/field-engine/group-sections.ts) - code-declared and never company-overridable, same as fieldType. Undefined for an entity that hasn't been split into sections yet (every field then stays in the flat `fields` response, as today). */
  section?: string;
}

/**
 * What core/field-engine/resolve.ts actually returns: a FieldDefault's
 * shape, further narrowed by the requesting user's RBAC field
 * permissions (core/rbac) - `isVisible`/`isEditable` here are the FINAL,
 * already-intersected values a form can trust directly, not just the
 * company-level override.
 */
export interface EffectiveField {
  id: string | undefined;
  module: string;
  entity: string;
  fieldKey: string;
  tier: 2;
  label: string;
  dataType: FieldDataType;
  isVisible: boolean;
  isMandatory: boolean;
  isEditable: boolean;
  defaultValue: string | undefined;
  optionsSource: FieldOptionsSource | undefined;
  fieldType: FieldType | undefined;
  multiple: boolean | undefined;
  allowCreate: boolean | undefined;
  validationJson: FieldValidationRules | undefined;
  sortOrder: number;
  isSystem: boolean;
  section: string | undefined;
}
