import { http, HttpResponse } from "msw";
import { fieldDefinitionsResponseSchema, masterOptionsResponseSchema, type FieldDefinitionsResponse } from "@ikration/contracts";
import { endpoints } from "../core/api/endpoints";
import { listHandler, updateHandler, type MockRow } from "./admin-handlers";

const API_BASE = import.meta.env.VITE_WEB_API_BASE_URL;

/** Mirrors apps/api's core/field-engine/defaults.ts brokers/broker entry field-for-field (Prompt 21 item 4). */
export const brokerFieldDefinitions: FieldDefinitionsResponse = fieldDefinitionsResponseSchema.parse({
  module: "brokers",
  entity: "broker",
  fields: [
    { fieldKey: "code", label: "Broker Code", dataType: "text", isMandatory: false, isEditable: false, isSystem: true, sortOrder: 0, fieldType: "AutoGenerated" },
    { fieldKey: "name", label: "Broker Name", dataType: "text", isMandatory: true, isEditable: true, isSystem: true, sortOrder: 1 },
    { fieldKey: "remarks", label: "Remarks", dataType: "textarea", isMandatory: false, isEditable: true, isSystem: false, sortOrder: 2 },
  ],
});

export function resolveBrokerFieldDefinitions(module: string, entity: string): FieldDefinitionsResponse | undefined {
  return module === brokerFieldDefinitions.module && entity === brokerFieldDefinitions.entity ? brokerFieldDefinitions : undefined;
}

const brokers: MockRow[] = [
  {
    id: "brk-1",
    code: "BRK-0001",
    name: "Gulf Broking LLC",
    remarks: "",
    status: "active",
    contacts: [{ contactPerson: "Sam Broker", mobile: "+971501234567", email: "sam@gulfbroking.test" }],
    banks: [{ details: "Bank of Test - Account 654321" }],
  },
  {
    id: "brk-2",
    code: "BRK-0002",
    name: "Asia Metals Broking",
    remarks: "",
    status: "active",
    contacts: [],
    banks: [],
  },
];

let nextBrokerId = 1000;

export const brokersHandlers = [
  http.get(`${API_BASE}${endpoints.brokers}`, listHandler(brokers)),
  http.get(`${API_BASE}${endpoints.brokerOptions}`, () =>
    HttpResponse.json(
      masterOptionsResponseSchema.parse({
        options: brokers.filter((row) => row.status === "active").map((row) => ({ value: row.id, label: String(row.name) })),
      }),
    ),
  ),
  http.get(`${API_BASE}${endpoints.brokers}/:id`, ({ params }) => {
    const row = brokers.find((candidate) => candidate.id === params.id);
    return row ? HttpResponse.json(row) : new HttpResponse(null, { status: 404 });
  }),
  http.post(`${API_BASE}${endpoints.brokers}`, async ({ request }) => {
    const body = (await request.json()) as Record<string, unknown>;
    // Mirrors brokers.validator.ts's createBrokerSchema exactly: remarks
    // is z.string().min(1).optional() - a genuinely absent key is fine, an
    // empty string is not. Catches the SchemaForm-level bug this guarded
    // against (an untouched optional Textarea defaulting to "" and being
    // submitted as-is) that a mock accepting anything would otherwise miss.
    if (body.remarks === "") {
      return HttpResponse.json(
        { error: { code: "VALIDATION_ERROR", message: "Validation failed", details: { issues: [{ path: ["remarks"], message: "Too small: expected string to have >=1 characters" }] } } },
        { status: 422 },
      );
    }
    if (brokers.some((row) => row.name === body.name)) {
      return HttpResponse.json(
        { error: { code: "CONFLICT", message: `A broker with the name "${String(body.name)}" already exists` } },
        { status: 409 },
      );
    }
    nextBrokerId += 1;
    const row: MockRow = { ...body, id: `brk-${nextBrokerId}`, code: `BRK-${String(nextBrokerId).padStart(4, "0")}`, status: "active" };
    brokers.push(row);
    return HttpResponse.json(row, { status: 201 });
  }),
  http.patch(`${API_BASE}${endpoints.brokers}/:id`, updateHandler(brokers)),
  http.patch(`${API_BASE}${endpoints.activateBroker(":id")}`, ({ params }) => {
    const row = brokers.find((candidate) => candidate.id === params.id);
    if (!row) {
      return new HttpResponse(null, { status: 404 });
    }
    row.status = "active";
    return HttpResponse.json(row);
  }),
  http.patch(`${API_BASE}${endpoints.deactivateBroker(":id")}`, ({ params }) => {
    const row = brokers.find((candidate) => candidate.id === params.id);
    if (!row) {
      return new HttpResponse(null, { status: 404 });
    }
    row.status = "inactive";
    return HttpResponse.json(row);
  }),
];
