import { http, HttpResponse } from "msw";
import {
  fieldDefinitionsResponseSchema,
  loginResponseSchema,
  meResponseSchema,
  refreshResponseSchema,
  type FieldDefinitionsResponse,
  type LoginResponse,
  type MeResponse,
} from "@hyperion/contracts";
import { endpoints } from "../core/api/endpoints";

const API_BASE = import.meta.env.VITE_API_BASE_URL;

/**
 * Fixture data is parsed through the same contract schemas the real API is
 * validated against - a typo or a shape drift here throws at module load
 * instead of quietly shipping a mock that no longer matches the contract.
 */
const mockUser: MeResponse = meResponseSchema.parse({
  id: "11111111-1111-4111-8111-111111111111",
  email: "demo.admin@hyperion.test",
  name: "Demo Admin",
  companyId: "22222222-2222-4222-8222-222222222222",
  status: "active",
});

const mockLoginResponse: LoginResponse = loginResponseSchema.parse({
  mustChangePassword: false,
  accessToken: "mock-access-token",
  refreshToken: "mock-refresh-token",
  user: {
    id: mockUser.id,
    email: mockUser.email,
    name: mockUser.name,
    companyId: mockUser.companyId,
  },
});

const mockFieldDefinitions: FieldDefinitionsResponse = fieldDefinitionsResponseSchema.parse({
  module: "purchase",
  entity: "purchase",
  version: 1,
  sections: [
    {
      key: "header",
      label: "Purchase Header",
      sortOrder: 1,
      fields: [
        {
          fieldKey: "purchaseNumber",
          tier: "fixed",
          label: "Purchase Number",
          fieldType: "AutoGenerated",
          dataType: "string",
          isMandatory: true,
          isEditable: false,
          isSystem: true,
          sortOrder: 1,
        },
        {
          fieldKey: "purchaseDate",
          tier: "fixed",
          label: "Purchase Date",
          fieldType: "DatePicker",
          dataType: "date",
          isMandatory: true,
          isEditable: true,
          isSystem: true,
          sortOrder: 2,
        },
      ],
    },
  ],
});

export const handlers = [
  http.post(`${API_BASE}${endpoints.login}`, () => HttpResponse.json(mockLoginResponse)),
  http.post(`${API_BASE}${endpoints.refresh}`, () =>
    HttpResponse.json(
      refreshResponseSchema.parse({
        accessToken: "mock-access-token-rotated",
        refreshToken: "mock-refresh-token-rotated",
      }),
    ),
  ),
  http.get(`${API_BASE}${endpoints.me}`, () => HttpResponse.json(mockUser)),
  http.get(`${API_BASE}${endpoints.fieldDefinitions(":module", ":entity")}`, () =>
    HttpResponse.json(mockFieldDefinitions),
  ),
];
