import { http, HttpResponse } from "msw";
import {
  changePasswordResponseSchema,
  fieldDefinitionModulesResponseSchema,
  fieldDefinitionsResponseSchema,
  loginResponseSchema,
  masterOptionsResponseSchema,
  menuTreeResponseSchema,
  meResponseSchema,
  myCompaniesResponseSchema,
  myPermissionsResponseSchema,
  paginatedRowsResponseSchema,
  refreshResponseSchema,
  validateInvitationResponseSchema,
  type ChangePasswordResponse,
  type FieldDefinitionsResponse,
  type LoginResponse,
  type MasterOption,
  type MeResponse,
  type MenuTreeResponse,
  type MyCompaniesResponse,
  type MyPermissionsResponse,
  type ValidateInvitationResponse,
} from "@ikration/contracts";
import { endpoints } from "../core/api/endpoints";
import { schemaFormDevFixture } from "../core/schema-form/dev-fixture";
import {
  DEV_ENTITY_LIST_ENDPOINT,
  schemaTableDevFieldDefinitions,
  schemaTableDevRows,
  type DevEntityRow,
} from "../core/schema-table/dev-fixture";
import { MASTER_REGISTRY } from "../modules/masters/master-registry";
import { mastersHandlers, resolveMasterFieldDefinitions, resolveMasterRowOptions } from "./masters-handlers";
import { adminHandlers, resolveAdminFieldDefinitions } from "./admin-handlers";
import { suppliersHandlers, resolveSupplierFieldDefinitions } from "./suppliers-handlers";
import { brokersHandlers, resolveBrokerFieldDefinitions } from "./brokers-handlers";
import { purchaseHandlers, resolvePurchaseFieldDefinitions } from "./purchase-handlers";
import { purchasePaymentsHandlers, PAYMENT_FIELDS } from "./purchase-payments-handlers";
import { inventoryHandlers } from "./inventory-handlers";
import { attachmentsHandlers } from "./attachments-handlers";

const API_BASE = import.meta.env.VITE_WEB_API_BASE_URL;

/**
 * Fixture data is parsed through the same contract schemas the real API is
 * validated against - a typo or a shape drift here throws at module load
 * instead of quietly shipping a mock that no longer matches the contract.
 */
const mockUser: MeResponse = meResponseSchema.parse({
  id: "11111111-1111-4111-8111-111111111111",
  email: "demo.admin@ikration.test",
  name: "Demo Admin",
  companyId: "22222222-2222-4222-8222-222222222222",
  status: "active",
});

const mockLoginResponse: LoginResponse = loginResponseSchema.parse({
  mustChangePassword: false,
  accessToken: "mock-access-token",
  refreshToken: "mock-refresh-token",
  user: {
    id: mockUser.id,
    email: mockUser.email,
    name: mockUser.name,
    companyId: mockUser.companyId,
  },
});

const mockChangePasswordResponse: ChangePasswordResponse = changePasswordResponseSchema.parse({
  accessToken: "mock-access-token-post-change",
  refreshToken: "mock-refresh-token-post-change",
  mustChangePassword: false,
});

const mockInvitation: ValidateInvitationResponse = validateInvitationResponseSchema.parse({
  email: "new.hire@ikration.test",
  companyName: "Ikration Metals Trading",
});

const mockCompanies: MyCompaniesResponse = myCompaniesResponseSchema.parse({
  companies: [
    {
      id: mockUser.companyId,
      name: "Ikration Metals Trading",
      branches: [
        { id: "33333333-3333-4333-8333-333333333333", name: "Dubai HQ" },
        { id: "44444444-4444-4444-8444-444444444444", name: "Jebel Ali Warehouse" },
      ],
    },
    {
      id: "55555555-5555-4555-8555-555555555555",
      name: "Ikration Singapore Pte Ltd",
      branches: [{ id: "66666666-6666-4666-8666-666666666666", name: "Singapore HQ" }],
    },
  ],
});

const mockFieldDefinitions: FieldDefinitionsResponse = fieldDefinitionsResponseSchema.parse({
  module: "purchase",
  entity: "purchase",
  version: 1,
  sections: [
    {
      key: "header",
      label: "Purchase Header",
      sortOrder: 1,
      fields: [
        {
          fieldKey: "purchaseNumber",
          tier: "fixed",
          label: "Purchase Number",
          fieldType: "AutoGenerated",
          dataType: "text",
          isMandatory: true,
          isEditable: false,
          isSystem: true,
          sortOrder: 1,
        },
        {
          fieldKey: "purchaseDate",
          tier: "fixed",
          label: "Purchase Date",
          fieldType: "DatePicker",
          dataType: "date",
          isMandatory: true,
          isEditable: true,
          isSystem: true,
          sortOrder: 2,
        },
      ],
    },
  ],
});

/**
 * The admin field-definitions picker's source list - mirrors the real
 * GET /field-definitions/modules's shape (every module/entity pair with
 * field definitions), not exhaustively every mocked entity, just a
 * representative set covering what this mock environment actually
 * serves.
 */
const mockFieldDefinitionModules = fieldDefinitionModulesResponseSchema.parse({
  modules: [
    { module: "purchase", entity: "header" },
    { module: "purchase", entity: "po" },
    { module: "purchase", entity: "item" },
    { module: "purchase", entity: "allocation" },
    { module: "purchase", entity: "lme_record" },
    { module: "purchase", entity: "hedge" },
    { module: "purchase", entity: "invoice" },
    { module: "suppliers", entity: "supplier" },
    { module: "brokers", entity: "broker" },
    { module: "admin", entity: "company" },
    { module: "admin", entity: "branch" },
    { module: "users", entity: "user" },
  ],
});

/**
 * Sub-groups masters within the launcher's "Masters" card - mirrors
 * seed-menu-tree.ts's own MASTER_LAUNCHER_GROUPS map. A master's
 * urlSegment not listed here falls back to "Logistics", same as the
 * backend, so a newly added master never disappears from the launcher.
 */
const MASTER_LAUNCHER_GROUPS: Record<string, string> = {
  countries: "Geography",
  cities: "Geography",
  ports: "Geography",
  currencies: "Commercial",
  "payment-terms": "Commercial",
  incoterms: "Commercial",
  uom: "Commercial",
  "lme-exchanges": "Trading",
  "hedge-platforms": "Trading",
  divisions: "Trading",
  "supplier-types": "Trading",
  warehouses: "Logistics",
  vessels: "Logistics",
  "transport-modes": "Logistics",
  containers: "Logistics",
  items: "Logistics",
  "item-grades": "Logistics",
  customers: "Logistics",
};

/**
 * Mirrors the shape (not the exact ids) of apps/api/src/core/provisioning/
 * seed-menu-tree.ts's default tenant tree - already permission/module-
 * filtered, per resolve.ts, so the mock represents what a fully-privileged
 * demo admin would receive. `section` ("operate" | "settings") and the
 * `launcherSection`/`launcherGroup` pair must stay in lockstep with
 * seed-menu-tree.ts's own tagging - the recurring drift bug CLAUDE.md
 * flags, now with three more fields to keep in sync.
 */
const mockMenuTree: MenuTreeResponse = menuTreeResponseSchema.parse({
  menus: [
    { id: "m-dashboard", key: "dashboard", label: "Dashboard", path: "/dashboard", icon: "dashboard", sortOrder: 1, section: "operate", launcherSection: null, launcherGroup: null, children: [] },
    { id: "m-suppliers", key: "suppliers", label: "Suppliers", path: "/suppliers", icon: "shop", sortOrder: 2, section: "operate", launcherSection: null, launcherGroup: null, children: [] },
    { id: "m-brokers", key: "brokers", label: "Brokers", path: "/brokers", icon: "contacts", sortOrder: 3, section: "operate", launcherSection: null, launcherGroup: null, children: [] },
    {
      id: "m-purchase",
      key: "purchase",
      label: "Purchase",
      path: null,
      icon: "shopping-cart",
      sortOrder: 4,
      section: "operate",
      launcherSection: null,
      launcherGroup: null,
      children: [
        {
          id: "m-purchase-orders",
          key: "purchase.orders",
          label: "Purchase Orders",
          path: "/purchase/orders",
          icon: "file-text",
          sortOrder: 1,
          section: "operate",
          launcherSection: null,
          launcherGroup: null,
          children: [],
        },
        // PL-4: Zoho's own "Purchase Receives" and "Bills" nav items -
        // must stay in lockstep with seed-menu-tree.ts's own two new
        // children (the recurring drift bug CLAUDE.md flags).
        {
          id: "m-purchase-receipts",
          key: "purchase.receipts",
          label: "Purchase Receipts",
          path: "/purchase/receipts",
          icon: "file-done",
          sortOrder: 2,
          section: "operate",
          launcherSection: null,
          launcherGroup: null,
          children: [],
        },
        {
          id: "m-purchase-bills",
          key: "purchase.bills",
          label: "Purchase Bills",
          path: "/purchase/bills",
          icon: "account-book",
          sortOrder: 3,
          section: "operate",
          launcherSection: null,
          launcherGroup: null,
          children: [],
        },
        // PL-5: Zoho's own "Payments Made" nav item - must stay in
        // lockstep with seed-menu-tree.ts's own new child (the recurring
        // drift bug CLAUDE.md flags).
        {
          id: "m-purchase-payments",
          key: "purchase.payments",
          label: "Payments Made",
          path: "/purchase/payments",
          icon: "dollar",
          sortOrder: 4,
          section: "operate",
          launcherSection: null,
          launcherGroup: null,
          children: [],
        },
      ],
    },
    { id: "m-inventory", key: "inventory", label: "Inventory", path: "/inventory", icon: "inbox", sortOrder: 5, section: "operate", launcherSection: null, launcherGroup: null, children: [] },
    // --- Settings (configure) - reached via the header gear, not the main
    // sidebar. See docs/PROMPT-settings-restructure.md.
    {
      id: "m-companies",
      key: "companies",
      label: "Companies",
      path: "/settings/companies",
      icon: "bank",
      sortOrder: 6,
      section: "settings",
      launcherSection: "Organization Settings",
      launcherGroup: "Organization",
      children: [],
    },
    {
      id: "m-branches",
      key: "branches",
      label: "Branches",
      path: "/settings/branches",
      icon: "apartment",
      sortOrder: 7,
      section: "settings",
      launcherSection: "Organization Settings",
      launcherGroup: "Organization",
      children: [],
    },
    {
      id: "m-users",
      key: "users",
      label: "Users",
      path: "/settings/users",
      icon: "users",
      sortOrder: 8,
      section: "settings",
      launcherSection: "Organization Settings",
      launcherGroup: "Users & Roles",
      children: [],
    },
    {
      id: "m-roles",
      key: "roles",
      label: "Roles",
      path: "/settings/roles",
      icon: "shield",
      sortOrder: 9,
      section: "settings",
      launcherSection: "Organization Settings",
      launcherGroup: "Users & Roles",
      children: [],
    },
    {
      id: "m-field-definitions",
      key: "field-definitions",
      label: "Field Definitions",
      path: "/settings/field-definitions",
      icon: "form",
      sortOrder: 10,
      section: "settings",
      launcherSection: "Organization Settings",
      launcherGroup: "Setup & Configuration",
      children: [],
    },
    {
      id: "m-number-series",
      key: "number-series",
      label: "Number Series",
      path: "/settings/number-series",
      icon: "ordered-list",
      sortOrder: 11,
      section: "settings",
      launcherSection: "Organization Settings",
      launcherGroup: "Setup & Configuration",
      children: [],
    },
    {
      id: "m-masters",
      key: "masters",
      label: "Masters",
      path: null,
      icon: "database",
      sortOrder: 12,
      section: "settings",
      launcherSection: null,
      launcherGroup: null,
      // Generated from the same registry MasterScreen resolves against
      // (modules/masters/master-registry.tsx) - the real backend seeds one
      // menu row per master the same way (core/provisioning/
      // seed-menu-tree.ts), so this mock stays honest about what "15
      // masters, one component" actually needs to render.
      children: MASTER_REGISTRY.map((master, index) => ({
        id: `m-masters-${master.urlSegment}`,
        key: `masters.${master.urlSegment}`,
        label: master.label,
        path: `/settings/masters/${master.urlSegment}`,
        icon: null,
        sortOrder: index + 1,
        section: "settings",
        launcherSection: "Master Data",
        launcherGroup: MASTER_LAUNCHER_GROUPS[master.urlSegment] ?? "Logistics",
        children: [],
      })),
    },
  ],
});

const mockPermissions: MyPermissionsResponse = myPermissionsResponseSchema.parse({
  permissions: [
    "users.user.read",
    "users.user.create",
    "users.user.update",
    "users.user.provision",
    "admin.company.read",
    "admin.company.create",
    "admin.company.update",
    "admin.branch.read",
    "admin.branch.create",
    "admin.branch.update",
    "admin.role.read",
    "admin.role.create",
    "admin.role.update",
    "admin.field.manage",
    "field_definitions.field.read",
    "purchase.po.read",
    "purchase.po.create",
    "purchase.po.update",
    "purchase.po.issue",
    "purchase.po.cancel",
    "purchase.invoice.create",
    "purchase.invoice.update",
    "purchase.invoice.approve",
    "purchase.receipt.create",
    "purchase.receipt.confirm",
    "purchase.payment.record",
    "inventory.stock.read",
    "suppliers.supplier.read",
    "suppliers.supplier.create",
    "suppliers.supplier.update",
    "brokers.broker.read",
    "brokers.broker.create",
    "brokers.broker.update",
    "storage.attachment.create",
    "storage.attachment.read",
    // Full CRUD on every master - matches core/masters/factory.ts's
    // permissionEntry("masters", entity, "create"|"read"|"update", ...).
    ...MASTER_REGISTRY.flatMap((master) => [
      `masters.${master.entity}.read`,
      `masters.${master.entity}.create`,
      `masters.${master.entity}.update`,
    ]),
  ],
});

const MASTER_OPTIONS: Record<string, MasterOption[]> = {
  countries: [
    { value: "ae", label: "United Arab Emirates" },
    { value: "sg", label: "Singapore" },
    { value: "in", label: "India" },
  ],
  cities: [
    { value: "dubai", label: "Dubai", parentValue: "ae" },
    { value: "abu-dhabi", label: "Abu Dhabi", parentValue: "ae" },
    { value: "singapore-city", label: "Singapore", parentValue: "sg" },
    { value: "mumbai", label: "Mumbai", parentValue: "in" },
  ],
  warehouses: [
    { value: "wh-1", label: "Jebel Ali Warehouse" },
    { value: "wh-2", label: "Singapore Bonded Warehouse" },
  ],
  currencies: [
    { value: "aed", label: "UAE Dirham" },
    { value: "sgd", label: "Singapore Dollar" },
    { value: "usd", label: "US Dollar" },
  ],
};

export const handlers = [
  http.post(`${API_BASE}${endpoints.login}`, () => HttpResponse.json(mockLoginResponse)),
  http.post(`${API_BASE}${endpoints.refresh}`, () =>
    HttpResponse.json(
      refreshResponseSchema.parse({
        accessToken: "mock-access-token-rotated",
        refreshToken: "mock-refresh-token-rotated",
      }),
    ),
  ),
  http.post(`${API_BASE}${endpoints.logout}`, () => new HttpResponse(null, { status: 204 })),
  http.get(`${API_BASE}${endpoints.me}`, () => HttpResponse.json(mockUser)),
  http.post(`${API_BASE}${endpoints.changePassword}`, () => HttpResponse.json(mockChangePasswordResponse)),
  http.get(`${API_BASE}${endpoints.myCompanies}`, () => HttpResponse.json(mockCompanies)),
  http.get(`${API_BASE}${endpoints.validateInvitation(":token")}`, () =>
    HttpResponse.json(mockInvitation),
  ),
  http.post(`${API_BASE}${endpoints.acceptInvitation(":token")}`, () => new HttpResponse(null, { status: 204 })),
  http.get(`${API_BASE}${endpoints.fieldDefinitionModules}`, () => HttpResponse.json(mockFieldDefinitionModules)),
  http.get(`${API_BASE}${endpoints.fieldDefinitions(":module", ":entity")}`, ({ params }) => {
    if (params.module === schemaFormDevFixture.module && params.entity === schemaFormDevFixture.entity) {
      return HttpResponse.json(schemaFormDevFixture);
    }
    if (
      params.module === schemaTableDevFieldDefinitions.module &&
      params.entity === schemaTableDevFieldDefinitions.entity
    ) {
      return HttpResponse.json(schemaTableDevFieldDefinitions);
    }
    const module = typeof params.module === "string" ? params.module : "";
    const entity = typeof params.entity === "string" ? params.entity : "";
    const masterFields = resolveMasterFieldDefinitions(module, entity);
    if (masterFields) {
      return HttpResponse.json(masterFields);
    }
    const adminFields = resolveAdminFieldDefinitions(module, entity);
    if (adminFields) {
      return HttpResponse.json(adminFields);
    }
    const supplierFields = resolveSupplierFieldDefinitions(module, entity);
    if (supplierFields) {
      return HttpResponse.json(supplierFields);
    }
    const brokerFields = resolveBrokerFieldDefinitions(module, entity);
    if (brokerFields) {
      return HttpResponse.json(brokerFields);
    }
    const purchaseFields = resolvePurchaseFieldDefinitions(module, entity);
    if (purchaseFields) {
      return HttpResponse.json(purchaseFields);
    }
    if (module === "purchase" && entity === "payment") {
      return HttpResponse.json(PAYMENT_FIELDS);
    }
    return HttpResponse.json(mockFieldDefinitions);
  }),
  http.get(`${API_BASE}${endpoints.menus}`, () => HttpResponse.json(mockMenuTree)),
  http.get(`${API_BASE}${endpoints.myPermissions}`, () => HttpResponse.json(mockPermissions)),
  http.get(`${API_BASE}${DEV_ENTITY_LIST_ENDPOINT}`, ({ request }) => {
    const url = new URL(request.url);
    const page = Number(url.searchParams.get("page") ?? "1");
    const pageSize = Number(url.searchParams.get("pageSize") ?? "20");
    const search = url.searchParams.get("search")?.toLowerCase();
    const isActiveParam = url.searchParams.get("isActive");
    const sortBy = url.searchParams.get("sortBy");
    const sortDir = url.searchParams.get("sortDir");

    let rows = [...schemaTableDevRows];
    if (search) {
      rows = rows.filter(
        (row) => row.name.toLowerCase().includes(search) || row.code.toLowerCase().includes(search),
      );
    }
    if (isActiveParam !== null) {
      rows = rows.filter((row) => String(row.isActive) === isActiveParam);
    }
    if (sortBy === "name" || sortBy === "code") {
      const key: "name" | "code" = sortBy;
      rows.sort((a, b) => {
        const cmp = a[key].localeCompare(b[key]);
        return sortDir === "desc" ? -cmp : cmp;
      });
    }

    const total = rows.length;
    const items: DevEntityRow[] = rows.slice((page - 1) * pageSize, (page - 1) * pageSize + pageSize);

    return HttpResponse.json(paginatedRowsResponseSchema.parse({ items, total, page, pageSize }));
  }),
  http.get(`${API_BASE}${endpoints.masterOptions(":master")}`, ({ params, request }) => {
    const master = typeof params.master === "string" ? params.master : "";
    const all = MASTER_OPTIONS[master] ?? resolveMasterRowOptions(master) ?? [];
    const url = new URL(request.url);
    const parentValue = url.searchParams.get("parentValue");
    const search = url.searchParams.get("search")?.toLowerCase();

    let filtered = all;
    if (parentValue) {
      filtered = filtered.filter((option) => option.parentValue === parentValue);
    }
    if (search) {
      filtered = filtered.filter((option) => option.label.toLowerCase().includes(search));
    }

    return HttpResponse.json(masterOptionsResponseSchema.parse({ options: filtered }));
  }),
  ...mastersHandlers,
  ...adminHandlers,
  ...suppliersHandlers,
  ...brokersHandlers,
  ...purchaseHandlers,
  ...purchasePaymentsHandlers,
  ...inventoryHandlers,
  ...attachmentsHandlers,
];
