import { http, HttpResponse } from "msw";
import {
  changePasswordResponseSchema,
  fieldDefinitionsResponseSchema,
  loginResponseSchema,
  masterOptionsResponseSchema,
  menuTreeResponseSchema,
  meResponseSchema,
  myCompaniesResponseSchema,
  myPermissionsResponseSchema,
  paginatedRowsResponseSchema,
  refreshResponseSchema,
  validateInvitationResponseSchema,
  type ChangePasswordResponse,
  type FieldDefinitionsResponse,
  type LoginResponse,
  type MasterOption,
  type MeResponse,
  type MenuTreeResponse,
  type MyCompaniesResponse,
  type MyPermissionsResponse,
  type ValidateInvitationResponse,
} from "@hyperion/contracts";
import { endpoints } from "../core/api/endpoints";
import { schemaFormDevFixture } from "../core/schema-form/dev-fixture";
import {
  DEV_ENTITY_LIST_ENDPOINT,
  schemaTableDevFieldDefinitions,
  schemaTableDevRows,
  type DevEntityRow,
} from "../core/schema-table/dev-fixture";
import { MASTER_REGISTRY } from "../modules/masters/master-registry";
import { mastersHandlers, resolveMasterFieldDefinitions } from "./masters-handlers";

const API_BASE = import.meta.env.VITE_API_BASE_URL;

/**
 * Fixture data is parsed through the same contract schemas the real API is
 * validated against - a typo or a shape drift here throws at module load
 * instead of quietly shipping a mock that no longer matches the contract.
 */
const mockUser: MeResponse = meResponseSchema.parse({
  id: "11111111-1111-4111-8111-111111111111",
  email: "demo.admin@hyperion.test",
  name: "Demo Admin",
  companyId: "22222222-2222-4222-8222-222222222222",
  status: "active",
});

const mockLoginResponse: LoginResponse = loginResponseSchema.parse({
  mustChangePassword: false,
  accessToken: "mock-access-token",
  refreshToken: "mock-refresh-token",
  user: {
    id: mockUser.id,
    email: mockUser.email,
    name: mockUser.name,
    companyId: mockUser.companyId,
  },
});

const mockChangePasswordResponse: ChangePasswordResponse = changePasswordResponseSchema.parse({
  accessToken: "mock-access-token-post-change",
  refreshToken: "mock-refresh-token-post-change",
  mustChangePassword: false,
});

const mockInvitation: ValidateInvitationResponse = validateInvitationResponseSchema.parse({
  email: "new.hire@hyperion.test",
  companyName: "Hyperion Metals Trading",
});

const mockCompanies: MyCompaniesResponse = myCompaniesResponseSchema.parse({
  companies: [
    {
      id: mockUser.companyId,
      name: "Hyperion Metals Trading",
      branches: [
        { id: "33333333-3333-4333-8333-333333333333", name: "Dubai HQ" },
        { id: "44444444-4444-4444-8444-444444444444", name: "Jebel Ali Warehouse" },
      ],
    },
    {
      id: "55555555-5555-4555-8555-555555555555",
      name: "Hyperion Singapore Pte Ltd",
      branches: [{ id: "66666666-6666-4666-8666-666666666666", name: "Singapore HQ" }],
    },
  ],
});

const mockFieldDefinitions: FieldDefinitionsResponse = fieldDefinitionsResponseSchema.parse({
  module: "purchase",
  entity: "purchase",
  version: 1,
  sections: [
    {
      key: "header",
      label: "Purchase Header",
      sortOrder: 1,
      fields: [
        {
          fieldKey: "purchaseNumber",
          tier: "fixed",
          label: "Purchase Number",
          fieldType: "AutoGenerated",
          dataType: "text",
          isMandatory: true,
          isEditable: false,
          isSystem: true,
          sortOrder: 1,
        },
        {
          fieldKey: "purchaseDate",
          tier: "fixed",
          label: "Purchase Date",
          fieldType: "DatePicker",
          dataType: "date",
          isMandatory: true,
          isEditable: true,
          isSystem: true,
          sortOrder: 2,
        },
      ],
    },
  ],
});

/** Mirrors the shape (not the exact ids) of apps/api/src/core/provisioning/seed-menu-tree.ts's default tenant tree - already permission/module-filtered, per resolve.ts, so the mock represents what a fully-privileged demo admin would receive. */
const mockMenuTree: MenuTreeResponse = menuTreeResponseSchema.parse({
  menus: [
    { id: "m-dashboard", key: "dashboard", label: "Dashboard", path: "/dashboard", icon: "dashboard", sortOrder: 1, children: [] },
    {
      id: "m-users",
      key: "users",
      label: "Users",
      path: null,
      icon: "users",
      sortOrder: 2,
      children: [
        { id: "m-users-list", key: "users.list", label: "All Users", path: "/users", icon: null, sortOrder: 1, children: [] },
        { id: "m-users-invite", key: "users.invite", label: "Invite User", path: "/users/invite", icon: null, sortOrder: 2, children: [] },
      ],
    },
    { id: "m-roles", key: "roles", label: "Roles", path: "/roles", icon: "shield", sortOrder: 3, children: [] },
    {
      id: "m-masters",
      key: "masters",
      label: "Masters",
      path: null,
      icon: "database",
      sortOrder: 4,
      // Generated from the same registry MasterScreen resolves against
      // (modules/masters/master-registry.tsx) - the real backend seeds one
      // menu row per master the same way (core/provisioning/
      // seed-menu-tree.ts), so this mock stays honest about what "15
      // masters, one component" actually needs to render.
      children: MASTER_REGISTRY.map((master, index) => ({
        id: `m-masters-${master.urlSegment}`,
        key: `masters.${master.urlSegment}`,
        label: master.label,
        path: `/masters/${master.urlSegment}`,
        icon: null,
        sortOrder: index + 1,
        children: [],
      })),
    },
    {
      id: "m-purchase",
      key: "purchase",
      label: "Purchase",
      path: null,
      icon: "shopping-cart",
      sortOrder: 5,
      children: [
        {
          id: "m-purchase-orders",
          key: "purchase.orders",
          label: "Purchase Orders",
          path: "/purchase/orders",
          icon: null,
          sortOrder: 1,
          children: [],
        },
      ],
    },
  ],
});

const mockPermissions: MyPermissionsResponse = myPermissionsResponseSchema.parse({
  permissions: [
    "users.user.read",
    "users.user.create",
    "roles.role.read",
    "purchase.po.read",
    "purchase.po.approve",
    // Full CRUD on every master - matches core/masters/factory.ts's
    // permissionEntry("masters", entity, "create"|"read"|"update", ...).
    ...MASTER_REGISTRY.flatMap((master) => [
      `masters.${master.entity}.read`,
      `masters.${master.entity}.create`,
      `masters.${master.entity}.update`,
    ]),
  ],
});

const MASTER_OPTIONS: Record<string, MasterOption[]> = {
  countries: [
    { value: "ae", label: "United Arab Emirates" },
    { value: "sg", label: "Singapore" },
    { value: "in", label: "India" },
  ],
  cities: [
    { value: "dubai", label: "Dubai", parentValue: "ae" },
    { value: "abu-dhabi", label: "Abu Dhabi", parentValue: "ae" },
    { value: "singapore-city", label: "Singapore", parentValue: "sg" },
    { value: "mumbai", label: "Mumbai", parentValue: "in" },
  ],
  warehouses: [
    { value: "wh-1", label: "Jebel Ali Warehouse" },
    { value: "wh-2", label: "Singapore Bonded Warehouse" },
  ],
};

export const handlers = [
  http.post(`${API_BASE}${endpoints.login}`, () => HttpResponse.json(mockLoginResponse)),
  http.post(`${API_BASE}${endpoints.refresh}`, () =>
    HttpResponse.json(
      refreshResponseSchema.parse({
        accessToken: "mock-access-token-rotated",
        refreshToken: "mock-refresh-token-rotated",
      }),
    ),
  ),
  http.post(`${API_BASE}${endpoints.logout}`, () => new HttpResponse(null, { status: 204 })),
  http.get(`${API_BASE}${endpoints.me}`, () => HttpResponse.json(mockUser)),
  http.post(`${API_BASE}${endpoints.changePassword}`, () => HttpResponse.json(mockChangePasswordResponse)),
  http.get(`${API_BASE}${endpoints.myCompanies}`, () => HttpResponse.json(mockCompanies)),
  http.get(`${API_BASE}${endpoints.validateInvitation(":token")}`, () =>
    HttpResponse.json(mockInvitation),
  ),
  http.post(`${API_BASE}${endpoints.acceptInvitation(":token")}`, () => new HttpResponse(null, { status: 204 })),
  http.get(`${API_BASE}${endpoints.fieldDefinitions(":module", ":entity")}`, ({ params }) => {
    if (params.module === schemaFormDevFixture.module && params.entity === schemaFormDevFixture.entity) {
      return HttpResponse.json(schemaFormDevFixture);
    }
    if (
      params.module === schemaTableDevFieldDefinitions.module &&
      params.entity === schemaTableDevFieldDefinitions.entity
    ) {
      return HttpResponse.json(schemaTableDevFieldDefinitions);
    }
    const module = typeof params.module === "string" ? params.module : "";
    const entity = typeof params.entity === "string" ? params.entity : "";
    const masterFields = resolveMasterFieldDefinitions(module, entity);
    if (masterFields) {
      return HttpResponse.json(masterFields);
    }
    return HttpResponse.json(mockFieldDefinitions);
  }),
  http.get(`${API_BASE}${endpoints.menus}`, () => HttpResponse.json(mockMenuTree)),
  http.get(`${API_BASE}${endpoints.myPermissions}`, () => HttpResponse.json(mockPermissions)),
  http.get(`${API_BASE}${DEV_ENTITY_LIST_ENDPOINT}`, ({ request }) => {
    const url = new URL(request.url);
    const page = Number(url.searchParams.get("page") ?? "1");
    const pageSize = Number(url.searchParams.get("pageSize") ?? "20");
    const search = url.searchParams.get("search")?.toLowerCase();
    const isActiveParam = url.searchParams.get("isActive");
    const sortBy = url.searchParams.get("sortBy");
    const sortDir = url.searchParams.get("sortDir");

    let rows = [...schemaTableDevRows];
    if (search) {
      rows = rows.filter(
        (row) => row.name.toLowerCase().includes(search) || row.code.toLowerCase().includes(search),
      );
    }
    if (isActiveParam !== null) {
      rows = rows.filter((row) => String(row.isActive) === isActiveParam);
    }
    if (sortBy === "name" || sortBy === "code") {
      const key: "name" | "code" = sortBy;
      rows.sort((a, b) => {
        const cmp = a[key].localeCompare(b[key]);
        return sortDir === "desc" ? -cmp : cmp;
      });
    }

    const total = rows.length;
    const items: DevEntityRow[] = rows.slice((page - 1) * pageSize, (page - 1) * pageSize + pageSize);

    return HttpResponse.json(paginatedRowsResponseSchema.parse({ items, total, page, pageSize }));
  }),
  http.get(`${API_BASE}${endpoints.masterOptions(":master")}`, ({ params, request }) => {
    const master = typeof params.master === "string" ? params.master : "";
    const all = MASTER_OPTIONS[master] ?? [];
    const url = new URL(request.url);
    const parentValue = url.searchParams.get("parentValue");
    const search = url.searchParams.get("search")?.toLowerCase();

    let filtered = all;
    if (parentValue) {
      filtered = filtered.filter((option) => option.parentValue === parentValue);
    }
    if (search) {
      filtered = filtered.filter((option) => option.label.toLowerCase().includes(search));
    }

    return HttpResponse.json(masterOptionsResponseSchema.parse({ options: filtered }));
  }),
  ...mastersHandlers,
];
