import { http, HttpResponse } from "msw";
import { fieldDefinitionsResponseSchema, paginatedRowsResponseSchema, type FieldDefinitionsResponse } from "@ikration/contracts";
import { endpoints } from "../core/api/endpoints";
import { purchases } from "./purchase-handlers";
import { paidAmountByBillId, payments, type MockPayment } from "./purchase-payments-store";

const API_BASE = import.meta.env.VITE_WEB_API_BASE_URL;

function asDisplayString(value: unknown): string {
  return typeof value === "string" || typeof value === "number" ? String(value) : "";
}

/** PL-5: mirrors core/field-engine/defaults.ts's real module="purchase" entity="payment" entry field-for-field. The repeating "which bill(s), how much applied to each" allocation grid is hand-built UI (PurchasePaymentForm), not a field-definitions field - same category as the Receipt/Bill forms' own outstanding-qty grids. */
export const PAYMENT_FIELDS: FieldDefinitionsResponse = fieldDefinitionsResponseSchema.parse({
  module: "purchase",
  entity: "payment",
  fields: [
    { fieldKey: "paymentNumber", label: "Payment Number", fieldType: "AutoGenerated", dataType: "text", isMandatory: false, isEditable: false, isSystem: true, sortOrder: 0 },
    { fieldKey: "supplierId", label: "Supplier", dataType: "select", isMandatory: true, isEditable: true, isSystem: false, sortOrder: 1, optionsSource: "suppliers" },
    { fieldKey: "paymentDate", label: "Payment Date", dataType: "date", isMandatory: true, isEditable: true, isSystem: false, sortOrder: 2 },
    {
      fieldKey: "paymentMode",
      label: "Payment Mode",
      dataType: "select",
      isMandatory: true,
      isEditable: true,
      isSystem: false,
      sortOrder: 3,
      optionsSource: {
        type: "enum",
        staticOptions: [
          { label: "Cash", value: "cash" },
          { label: "Cheque", value: "cheque" },
          { label: "Bank Transfer", value: "bank_transfer" },
          { label: "Other", value: "other" },
        ],
      },
    },
    { fieldKey: "referenceNumber", label: "Reference Number", dataType: "text", isMandatory: false, isEditable: true, isSystem: false, sortOrder: 4 },
    { fieldKey: "notes", label: "Notes", fieldType: "TextArea", dataType: "textarea", isMandatory: false, isEditable: true, isSystem: false, sortOrder: 5 },
  ],
});

let nextPaymentSequence = 1;
let nextAllocationSequence = 1;

/** Every APPROVED, not-yet-fully-paid bill for a given supplier, across every one of that supplier's purchases - mirrors the real backend's listOutstandingBillsForSupplier. */
function outstandingBillsForSupplier(supplierId: string): Record<string, unknown>[] {
  const paidByBillId = paidAmountByBillId();
  const rows: Record<string, unknown>[] = [];
  for (const purchase of purchases) {
    if (purchase.supplierId !== supplierId) {
      continue;
    }
    for (const invoice of purchase.invoices) {
      if (invoice.status !== "approved") {
        continue;
      }
      const billId = String(invoice.id);
      const billAmountUsd = Number(invoice.invoiceAmountUsd ?? "0");
      const paidAmountUsd = paidByBillId.get(billId) ?? 0;
      if (paidAmountUsd >= billAmountUsd) {
        continue;
      }
      rows.push({
        id: billId,
        purchaseId: purchase.id,
        purchaseNumber: purchase.purchaseNumber,
        billNumber: invoice.invoiceNumber,
        billDate: invoice.invoiceDate,
        dueDate: invoice.dueDate ?? null,
        billAmountUsd: billAmountUsd.toFixed(2),
        paidAmountUsd: paidAmountUsd.toFixed(2),
        outstandingAmountUsd: (billAmountUsd - paidAmountUsd).toFixed(2),
      });
    }
  }
  return rows;
}

/** Once a bill's total applied payments reach its own invoiceAmountUsd, transition it to "approved" -> "paid" - mirrors the real backend's auto-transition inside purchase-payments.service.ts's create(). */
function maybeMarkBillsPaid(billIds: string[]): void {
  const paidByBillId = paidAmountByBillId();
  for (const purchase of purchases) {
    for (const invoice of purchase.invoices) {
      const billId = String(invoice.id);
      if (!billIds.includes(billId)) {
        continue;
      }
      const billAmountUsd = Number(invoice.invoiceAmountUsd ?? "0");
      const paidAmountUsd = paidByBillId.get(billId) ?? 0;
      if (paidAmountUsd >= billAmountUsd) {
        invoice.status = "paid";
      }
    }
  }
}

function findBillById(billId: string): Record<string, unknown> | undefined {
  for (const purchase of purchases) {
    const invoice = purchase.invoices.find((candidate) => candidate.id === billId);
    if (invoice) {
      return invoice;
    }
  }
  return undefined;
}

export const purchasePaymentsHandlers = [
  http.get(`${API_BASE}${endpoints.outstandingBillsForSupplier(":supplierId")}`, ({ params }) => {
    const supplierId = typeof params.supplierId === "string" ? params.supplierId : "";
    return HttpResponse.json({ items: outstandingBillsForSupplier(supplierId) });
  }),

  http.get(`${API_BASE}${endpoints.payments}`, ({ request }) => {
    const url = new URL(request.url);
    const page = Number(url.searchParams.get("page") ?? "1");
    const pageSize = Number(url.searchParams.get("pageSize") ?? "20");
    const supplierId = url.searchParams.get("supplierId");

    let filtered = payments;
    if (supplierId) {
      filtered = filtered.filter((payment) => payment.supplierId === supplierId);
    }
    const total = filtered.length;
    const items = filtered
      .slice()
      .reverse()
      .slice((page - 1) * pageSize, (page - 1) * pageSize + pageSize);
    return HttpResponse.json(paginatedRowsResponseSchema.parse({ items, total, page, pageSize }));
  }),

  http.get(`${API_BASE}${endpoints.payment(":id")}`, ({ params }) => {
    const payment = payments.find((candidate) => candidate.id === params.id);
    return payment ? HttpResponse.json(payment) : new HttpResponse(null, { status: 404 });
  }),

  http.post(`${API_BASE}${endpoints.payments}`, async ({ request }) => {
    const body = (await request.json()) as {
      supplierId: string;
      paymentDate: string;
      paymentMode: string;
      referenceNumber?: string;
      notes?: string;
      allocations: { billId: string; appliedAmountUsd: string }[];
    };

    const paidByBillId = paidAmountByBillId();
    let runningTotal = 0;
    for (const allocation of body.allocations) {
      const bill = findBillById(allocation.billId);
      if (!bill) {
        return HttpResponse.json({ error: { code: "NOT_FOUND", message: `Bill ${allocation.billId} not found` } }, { status: 404 });
      }
      if (bill.status !== "approved") {
        return HttpResponse.json(
          {
            error: {
              code: "CONFLICT",
              message: `Bill ${asDisplayString(bill.invoiceNumber)} is "${asDisplayString(bill.status)}" - only an approved bill can be paid`,
            },
          },
          { status: 409 },
        );
      }
      const billAmountUsd = Number(bill.invoiceAmountUsd ?? "0");
      const alreadyPaid = paidByBillId.get(allocation.billId) ?? 0;
      const outstanding = billAmountUsd - alreadyPaid;
      const appliedAmount = Number(allocation.appliedAmountUsd);
      if (appliedAmount > outstanding) {
        return HttpResponse.json(
          {
            error: {
              code: "CONFLICT",
              message: `Cannot apply ${appliedAmount} to bill ${asDisplayString(bill.invoiceNumber)}: only ${outstanding.toFixed(2)} remains outstanding`,
            },
          },
          { status: 409 },
        );
      }
      runningTotal += appliedAmount;
    }

    nextPaymentSequence += 1;
    const payment: MockPayment = {
      id: `payment-${nextPaymentSequence}`,
      paymentNumber: `PAY-2024-${String(nextPaymentSequence).padStart(4, "0")}`,
      supplierId: body.supplierId,
      paymentDate: body.paymentDate,
      paymentMode: body.paymentMode,
      ...(body.referenceNumber ? { referenceNumber: body.referenceNumber } : {}),
      ...(body.notes ? { notes: body.notes } : {}),
      paymentAmountUsd: runningTotal.toFixed(2),
      allocations: body.allocations.map((allocation) => {
        nextAllocationSequence += 1;
        return {
          id: `payment-allocation-${nextAllocationSequence}`,
          paymentId: `payment-${nextPaymentSequence}`,
          billId: allocation.billId,
          appliedAmountUsd: Number(allocation.appliedAmountUsd).toFixed(2),
        };
      }),
    };
    payments.push(payment);
    maybeMarkBillsPaid(body.allocations.map((allocation) => allocation.billId));

    return HttpResponse.json(payment, { status: 201 });
  }),
];
